window.trackList = [
  { id: 'cybersecurity', num: '01', title: 'Cybersecurity', color: '#38bdf8', desc: 'حماية الأنظمة والشبكات والبيانات من الهجمات الرقمية' },
  { id: 'software-development', num: '02', title: 'Software Development', color: '#4ade80', desc: 'تصميم وبناء وتطوير التطبيقات والبرمجيات' },
  { id: 'data-science-ai', num: '03', title: 'Data Science & AI', color: '#fbbf24', desc: 'تحليل البيانات وبناء نماذج الذكاء الاصطناعي' },
  { id: 'cloud-computing', num: '04', title: 'Cloud Computing', color: '#60a5fa', desc: 'الحوسبة السحابية وإدارة البنية التحتية' },
  { id: 'systems-administration', num: '05', title: 'Systems Administration', color: '#a78bfa', desc: 'إدارة أنظمة التشغيل والخوادم والشبكات' },
  { id: 'electronics', num: '06', title: 'Electronics & Embedded', color: '#f472b6', desc: 'الإلكترونيات والأنظمة المدمجة وإنترنت الأشياء' },
  { id: 'digital-arts', num: '07', title: 'Digital Arts', color: '#fb923c', desc: 'التصميم الرقمي والجرافيك والموشن' },
  { id: 'digital-marketing', num: '08', title: 'Digital Marketing', color: '#22d3ee', desc: 'التسويق الرقمي وتحسين محركات البحث' },
];

window.trackContent = {
  cybersecurity: {
    intro: {
      title: 'Cybersecurity Track',
      subtitle: 'الأمن السيبراني',
      whatIs: 'الأمن السيبراني (Cybersecurity) هو مجال حماية الأنظمة والشبكات والبرامج والبيانات من الهجمات الرقمية. الهدف منه منع المخترقين (Hackers) من الوصول غير المصرح به، أو التخريب، أو سرقة المعلومات الحساسة.',
      whatIsEn: 'Cybersecurity is the practice of protecting systems, networks, programs, and data from digital attacks, unauthorized access, damage, or theft.',
      importance: [
        { reason: 'تزايد الهجمات الإلكترونية', detail: 'هجوم يحدث كل 11 ثانية عالميًا' },
        { reason: 'التكاليف الباهظة', detail: 'متوسط تكلفة اختراق البيانات $4.45 مليون (2023)' },
        { reason: 'حماية الخصوصية', detail: 'حماية معلومات الأفراد والشركات' },
        { reason: 'الأمن القومي', detail: 'حماية البنية التحتية الحيوية للدول' },
      ],
      applications: ['الشركات والمؤسسات', 'البنوك والقطاع المالي', 'الحكومات', 'الرعاية الصحية', 'التجارة الإلكترونية'],
      careers: [
        { title: 'Security Analyst', salary: '10k - 25k ج.م', salaryInt: '$70k - $100k' },
        { title: 'Penetration Tester', salary: '15k - 35k ج.م', salaryInt: '$90k - $130k' },
        { title: 'SOC Analyst', salary: '8k - 20k ج.م', salaryInt: '$65k - $95k' },
        { title: 'Security Engineer', salary: '15k - 40k ج.م', salaryInt: '$100k - $150k' },
        { title: 'CISO', salary: '40k - 80k+ ج.م', salaryInt: '$180k - $250k+' },
      ],
      roadmap: [
        { level: 'Beginner', period: '0-6 Months', items: ['Networking Basics (OSI, TCP/IP)', 'Linux & Windows Basics', 'CIA Triad & Security Fundamentals', 'CompTIA Security+'] },
        { level: 'Foundation', period: '6-12 Months', items: ['Network Security', 'Ethical Hacking', 'Kali Linux, Nmap, Metasploit', 'Certified Ethical Hacker (CEH)'] },
        { level: 'Intermediate', period: '12-18 Months', items: ['Web App Security (OWASP Top 10)', 'SOC Operations', 'Incident Response', 'CompTIA CySA+'] },
        { level: 'Advanced', period: '18-24 Months', items: ['Cloud Security & DevSecOps', 'Digital Forensics', 'Malware Analysis', 'OSCP'] },
        { level: 'Professional', period: '24+ Months', items: ['Security Architecture', 'GRC & Compliance', 'CISSP, CISM', 'C-level Leadership'] },
      ],
    },
    modules: [
      { id: 'net-sec', title: 'Network Security Fundamentals', level: 'مبتدئ', time: '15 ساعة', cert: 'CCNA Security',
        overviewAr: 'أساسيات أمن الشبكات: كيف نحمي الشبكات من الاختراق وكيف نؤمن نقل البيانات.', 
        overviewEn: 'Network Security is a set of hardware and software technologies designed to protect the network infrastructure.',
        why: '95% من الهجمات الإلكترونية تبدأ من الشبكة. إذا لم تؤمن شبكتك، فأنت تترك باب بيتك مفتوحًا.',
        concepts: ['CIA Triad', 'Firewalls (Packet Filtering, Stateful, Next-Gen)', 'VPN', 'IDS/IPS', 'Zero Trust', 'Network Segmentation', 'AAA (Authentication, Authorization, Accounting)'],
        tools: ['Cisco Firepower', 'pfSense', 'Snort', 'Wireshark', 'OpenVPN'],
        applications: ['تأمين التحويلات المالية بين فروع البنوك', 'حماية شبكة الحرم الجامعي', 'تأمين اتصال الموظفين عن بُعد عبر VPN'],
        mistakes: ['إعداد Firewalls بدون قواعد واضحة', 'إهمال تحديث أجهزة الشبكة', 'عدم تقسيم الشبكة (Segmentation)'],
        summary: 'أمن الشبكات هو خط الدفاع الأول. بدون شبكة آمنة، كل شيء آخر معرض للخطر.'
      },
      { id: 'eth-hack', title: 'Ethical Hacking & Penetration Testing', level: 'متوسط', time: '20 ساعة', cert: 'CEH / OSCP',
        overviewAr: 'الاختراق الأخلاقي: محاكاة هجمات حقيقية على الأنظمة بهدف اكتشاف الثغرات قبل أن يكتشفها المخترقون الحقيقيون.',
        overviewEn: 'Ethical Hacking is the authorized practice of bypassing system security to identify potential data breaches and threats.',
        why: 'لمعرفة نقاط ضعف نظامك، يجب أن تهاجمه بنفسك قبل أن يهاجمك الآخرون.',
        concepts: ['Reconnaissance', 'Scanning & Enumeration', 'Exploitation', 'Privilege Escalation', 'Post-Exploitation', 'Reporting'],
        tools: ['Kali Linux', 'Nmap', 'Metasploit Framework', 'Burp Suite', 'John the Ripper', 'Hydra'],
        applications: ['Bug Bounty programs (Google pays millions)', 'اختبار أنظمة البنوك', 'Red Teaming للمؤسسات الكبيرة'],
        mistakes: ['عدم الحصول على إذن كتابي قبل الاختبار', 'إهمال مرحلة التوثيق', 'التسرع في الاستغلال بدون معلومات كافية'],
        summary: 'فكر مثل الهاكر، تصرف مثل المحترف. الاختراق الأخلاقي ضروري لأي مؤسسة جادة في أمنها.'
      },
      { id: 'forensics', title: 'Digital Forensics & Incident Response', level: 'متوسط', time: '12 ساعة', cert: 'CHFI',
        overviewAr: 'التحقيق الرقمي: جمع وتحليل الأدلة الرقمية بعد وقوع هجوم إلكتروني.',
        overviewEn: 'Digital Forensics is the process of identifying, preserving, analyzing, and presenting digital evidence.',
        why: 'بعد أي اختراق، السؤال الأول هو: ماذا حدث؟ كيف دخل؟ ماذا أخذ؟',
        concepts: ['Chain of Custody', 'Disk Forensics', 'Memory Forensics', 'Network Forensics', 'Malware Analysis', 'Incident Response Lifecycle'],
        tools: ['FTK Imager', 'Autopsy', 'Volatility', 'Splunk', 'YARA'],
        applications: ['تقديم أدلة رقمية في المحاكم', 'التحقق من صحة مطالبات الاختراق', 'التحقيق في جرائم الإنترنت'],
        mistakes: ['تعديل الأدلة الرقمية بدون قصد', 'إهمال توثيق خطوات التحقيق', 'عدم عمل نسخة (Image) قبل التحليل'],
        summary: 'كل هجوم يترك آثارًا. التحقيق الرقمي يعرفك من ومتى وكيف.'
      },
      { id: 'soc', title: 'Security Operations (SOC)', level: 'متوسط-متقدم', time: '15 ساعة', cert: 'CompTIA CySA+',
        overviewAr: 'مركز عمليات الأمن (SOC): غرفة التحكم التي تراقب الأنظمة 24/7 وتستجيب للتهديدات.',
        overviewEn: 'A Security Operations Center (SOC) is a centralized unit that monitors, detects, analyzes, and responds to cybersecurity incidents.',
        why: 'الهجمات لا تنتظر. SOC يضمن اكتشاف التهديدات في دقائق وليس أيامًا.',
        concepts: ['SIEM', 'SOAR', 'Threat Intelligence', 'Tier 1/2/3 Analysts', 'Playbooks', 'KPIs (MTTR)'],
        tools: ['Splunk / ELK Stack', 'IBM QRadar', 'TheHive', 'MISP', 'Wazuh'],
        applications: ['شركات الاتصالات تراقب ملايين المستخدمين', 'اكتشاف الاحتيال المالي في الوقت الفعلي', 'حماية مئات آلاف العملاء في السحابة'],
        mistakes: ['تجاهل False Positives', 'عدم تحديث قواعد الكشف', 'الاعتماد على أدوات بدون خبرة بشرية'],
        summary: 'SOC هو عين المؤسسة التي لا تنام. 24/7.'
      },
      { id: 'crypto', title: 'Cryptography & PKI', level: 'مبتدئ', time: '10 ساعة', cert: 'None directly',
        overviewAr: 'التشفير: علم إخفاء المعلومات بحيث لا يمكن قراءتها إلا من قبل الشخص المخول.',
        overviewEn: 'Cryptography is the practice and study of techniques for secure communication in the presence of adversaries.',
        why: 'بدون التشفير، كل ما تفعله على الإنترنت يمكن لأي شخص قراءته.',
        concepts: ['Symmetric Encryption (AES)', 'Asymmetric Encryption (RSA, ECC)', 'Hash Functions (SHA-256)', 'Digital Signatures', 'PKI', 'SSL/TLS', 'Certificate Authority'],
        tools: ['OpenSSL', 'GnuPG (GPG)', 'VeraCrypt', 'HashCat', 'Let\'s Encrypt'],
        applications: ['HTTPS (كل المواقع)', 'WhatsApp End-to-End Encryption', 'Bitcoin والعملات الرقمية'],
        mistakes: ['استخدام خوارزميات قديمة (MD5, DES)', 'تخزين المفاتيح الخاصة بشكل غير آمن', 'عدم تجديد الشهادات'],
        summary: 'التشفير هو أساس الثقة في العالم الرقمي.'
      },
    ],
    glossary: [
      { term: 'Cybersecurity', arabic: 'الأمن السيبراني', explanation: 'حماية الأنظمة والشبكات والبيانات من الهجمات الرقمية', category: 'أساسيات' },
      { term: 'Threat', arabic: 'تهديد', explanation: 'أي شيء يمكن أن يسبب ضررًا للنظام', category: 'أساسيات' },
      { term: 'Vulnerability', arabic: 'ثغرة أمنية', explanation: 'نقطة ضعف في النظام يمكن استغلالها', category: 'أساسيات' },
      { term: 'Risk', arabic: 'مخاطرة', explanation: 'احتمال أن تستغل ثغرة ما وتسبب ضررًا', category: 'أساسيات' },
      { term: 'Exploit', arabic: 'استغلال', explanation: 'كود أو أسلوب يستغل ثغرة معينة', category: 'أساسيات' },
      { term: 'Breach', arabic: 'اختراق', explanation: 'نجاح المهاجم في الوصول غير المصرح به', category: 'أساسيات' },
      { term: 'Firewall', arabic: 'جدار ناري', explanation: 'يمنع حركة المرور غير المصرح بها', category: 'أدوات' },
      { term: 'Encryption', arabic: 'تشفير', explanation: 'تحويل البيانات لشيفرة غير مفهومة', category: 'تشفير' },
      { term: 'Decryption', arabic: 'فك تشفير', explanation: 'تحويل الشيفرة إلى نص مفهوم', category: 'تشفير' },
      { term: 'Malware', arabic: 'برمجيات خبيثة', explanation: 'برامج ضارة (فيروسات، ديدان، أحصنة طروادة)', category: 'هجمات' },
      { term: 'Ransomware', arabic: 'برنامج فدية', explanation: 'يشفر بياناتك ويطلب فدية لفك التشفير', category: 'هجمات' },
      { term: 'Phishing', arabic: 'تصيد', explanation: 'خداع المستخدم لإعطاء معلوماته عبر رسائل مزيفة', category: 'هجمات' },
      { term: 'DDoS', arabic: 'هجوم حجب الخدمة', explanation: 'إغراق الخادم بطلبات لتعطيله', category: 'هجمات' },
      { term: 'VPN', arabic: 'شبكة خاصة افتراضية', explanation: 'يشفر الاتصال بين جهازك والخادم', category: 'أدوات' },
      { term: 'SIEM', arabic: 'نظام إدارة الأحداث الأمنية', explanation: 'يجمع ويحلل السجلات من مصادر متعددة', category: 'أدوات' },
      { term: 'Zero Day', arabic: 'ثغرة اليوم صفر', explanation: 'ثغرة لم تكتشف بعد من قبل الشركة المصنعة', category: 'هجمات' },
      { term: 'Social Engineering', arabic: 'هندسة اجتماعية', explanation: 'خداع البشر بدلاً من اختراق الأنظمة', category: 'هجمات' },
      { term: 'Penetration Testing', arabic: 'اختبار اختراق', explanation: 'محاكاة هجوم حقيقي لاختبار الأمن', category: 'ممارسات' },
      { term: 'Incident Response', arabic: 'استجابة للحوادث', explanation: 'إجراءات منظمة للتعامل مع الاختراقات', category: 'ممارسات' },
      { term: 'Digital Forensics', arabic: 'التحقيق الرقمي', explanation: 'جمع وتحليل الأدلة الرقمية بعد الاختراق', category: 'ممارسات' },
    ],
    tools: [
      { name: 'Nmap', desc: 'أداة مسح الشبكات واكتشاف الأجهزة والخدمات', use: 'أول خطوة في أي اختبار اختراق', pros: ['مجاني', 'قوي جدًا', 'مفتوح المصدر'], cons: ['قد تكتشفه أنظمة الحماية', 'يتطلب فهمًا للشبكات'], alt: 'Masscan, Zenmap', demand: 'مرتفع جدًا' },
      { name: 'Wireshark', desc: 'تحليل حركة الشبكة والتقاط الحزم', use: 'تحليل مشاكل الشبكة والكشف عن الهجمات', pros: ['مجاني', 'واجهة رسومية ممتازة', 'يدعم مئات البروتوكولات'], cons: ['كمية بيانات ضخمة قد تكون مربكة', 'لا يمنع الهجمات (مراقبة فقط)'], alt: 'Tcpdump, TShark', demand: 'مرتفع جدًا' },
      { name: 'Kali Linux', desc: 'نظام تشغيل متخصص بـ 600+ أداة أمنية', use: 'المنصة الرئيسية لاختبار الاختراق', pros: ['مجاني', 'كل الأدوات مثبتة مسبقًا', 'مجتمع ضخم'], cons: ['يتطلب معرفة Linux', 'قد يكون معقدًا للمبتدئين'], alt: 'Parrot OS, BlackArch', demand: 'عالي جدًا' },
      { name: 'Metasploit', desc: 'إطار عمل لاستغلال الثغرات', use: 'بعد تحديد الثغرات، لاستغلالها واختبار الاختراق', pros: ['قاعدة بيانات ضخمة من exploits', 'أتمتة متقدمة', 'مجاني للنسخة الأساسية'], cons: ['النسخة Pro مدفوعة', 'قد تكتشفه برامج الحماية'], alt: 'Core Impact, ExploitDB', demand: 'عالي جدًا' },
      { name: 'Burp Suite', desc: 'أداة اختبار أمن تطبيقات الويب', use: 'اختبار تطبيقات الويب APIs', pros: ['Proxy قوي', 'Repeater للاختبار اليدوي', 'Scanner آلي'], cons: ['النسخة الاحترافية مدفوعة', 'يحتاج خبرة في تطبيقات الويب'], alt: 'OWASP ZAP, Acunetix', demand: 'مرتفع' },
      { name: 'Splunk', desc: 'منصة تحليل سجلات و SIEM', use: 'في SOC لتحليل ملايين السجلات', pros: ['قوي جدًا', 'لوحات معلومات ممتازة', 'مجتمع كبير'], cons: ['مكلف للغاية', 'يتطلب تعلم لغة SPL'], alt: 'ELK Stack, Wazuh', demand: 'مرتفع جدًا' },
    ],
    interview: [
      { type: 'hr', q: 'عرفنا عن نفسك', a: 'أنا خريج هندسة / حاسبات، مهتم بمجال الأمن السيبراني. أكملت تدريب NTI Summer Training في مسار Cybersecurity واكتسبت مهارات عملية في Network Security و Ethical Hacking.' },
      { type: 'hr', q: 'لماذا تريد العمل في الأمن السيبراني؟', a: 'لأن العالم يتحول رقميًا بسرعة، ومع هذا التحول تزداد الهجمات الإلكترونية. أشعر أن هذا المجال يجمع بين التحدي الفكري والمسؤولية المجتمعية.' },
      { type: 'hr', q: 'أين ترى نفسك بعد 5 سنوات؟', a: 'أطمح لأن أصبح Security Architect أو Lead Penetration Tester. أخطط للحصول على شهادات CEH و OSCP ثم CISSP.' },
      { type: 'technical', q: 'اشرح CIA Triad', a: 'Confidentiality (السرية): فقط المصرح لهم يرون البيانات. Integrity (السلامة): البيانات لم تتغير. Availability (التوفر): البيانات متاحة عند الحاجة.', difficulty: 'easy' },
      { type: 'technical', q: 'ما الفرق بين IDS و IPS؟', a: 'IDS يكشف الهجمات وينبه فقط (Passive). IPS يمنع الهجمات تلقائيًا (Active - Inline). مثال: IDS مثل كاميرا مراقبة، IPS مثل حارس أمن.', difficulty: 'easy' },
      { type: 'technical', q: 'ما هي مراحل اختبار الاختراق؟', a: '1. Reconnaissance (جمع معلومات)\n2. Scanning (مسح)\n3. Exploitation (استغلال)\n4. Privilege Escalation (رفع صلاحيات)\n5. Post-Exploitation\n6. Reporting (توثيق)', difficulty: 'medium' },
      { type: 'technical', q: 'اشرح OWASP Top 10', a: 'أشهر 10 ثغرات في تطبيقات الويب: Broken Access Control, Cryptographic Failures, Injection, Insecure Design, Security Misconfiguration, Vulnerable Components, Auth Failures, Data Integrity Failures, Logging Failures, SSRF', difficulty: 'medium' },
      { type: 'scenario', q: 'وجدت أن موقع الشركة مخترق وعليه كلمة "Hacked by Anonymous". ماذا تفعل؟', a: '1. عزل الخادم فورًا\n2. إبلاغ فريق Incident Response\n3. أخذ صورة من الذاكرة والقرص\n4. تحليل السجلات لمعرفة مصدر الاختراق\n5. تغيير كل كلمات المرور\n6. إعادة بناء الموقع من نسخة احتياطية نظيفة\n7. تقرير Post-Mortem', difficulty: 'hard' },
      { type: 'scenario', q: 'موظف أبلغ أنه فتح ملف Excel غريب من إيميل مجهول. ماذا تفعل؟', a: '1. افترض أن الجهاز مخترق (Assume Breach)\n2. عزل الجهاز عن الشبكة فورًا\n3. أخذ صورة من الذاكرة والقرص\n4. تحليل الملف في Sandbox\n5. فحص النظام باستخدام EDR\n6. إذا تأكد وجود Malware، ابدأ Incident Response', difficulty: 'hard' },
    ],
    career: [
      { level: 'Junior', exp: '0-2 years', title: 'SOC Analyst / Jr. Penetration Tester', salary: '5k - 12k ج.م', skills: ['Networking Basics', 'Linux Basics', 'Nmap, Wireshark', 'CIA Triad'], certs: ['CompTIA Security+'] },
      { level: 'Mid-Level', exp: '2-5 years', title: 'Security Engineer', salary: '12k - 25k ج.م', skills: ['Firewalls, VPNs', 'Ethical Hacking', 'Python Scripting', 'SIEM (Splunk)'], certs: ['CEH', 'CompTIA CySA+'] },
      { level: 'Senior', exp: '5-8 years', title: 'Senior Security Engineer', salary: '25k - 45k ج.م', skills: ['Cloud Security', 'DevSecOps', 'Malware Analysis', 'Team Leadership'], certs: ['CISSP', 'OSCP'] },
      { level: 'Lead', exp: '8+ years', title: 'Security Architect / CISO', salary: '40k - 80k+ ج.م', skills: ['Enterprise Security', 'GRC', 'Strategy', 'Board Communication'], certs: ['CISSP', 'CISM'] },
    ],
    revision: {
      keyConcepts: ['CIA Triad: Confidentiality, Integrity, Availability', 'Defense in Depth: طبقات متعددة من الأمن', 'Zero Trust: لا تثق بأحد، تحقق من الجميع'],
      importantTerms: ['Threat vs Vulnerability vs Risk', 'Black Hat vs White Hat vs Gray Hat', 'IDS vs IPS', 'Symmetric vs Asymmetric Encryption'],
      mustTools: ['Nmap (مسح)', 'Wireshark (تحليل)', 'Kali Linux (منصة)', 'Metasploit (استغلال)', 'Burp Suite (ويب)', 'Splunk (SIEM)'],
      interviewNuggets: ['اعرف CIA Triad حفظًا وشرحًا', 'اعرف OWASP Top 10', 'جهز سيناريو Incident Response', 'تدرب على TryHackMe / Hack The Box'],
    },
  },
  'software-development': {
    intro: {
      title: 'Software Development Track',
      subtitle: 'تطوير البرمجيات',
      whatIs: 'تطوير البرمجيات هو عملية إنشاء برامج الكمبيوتر والتطبيقات التي نستخدمها يوميًا. من تطبيقات الموبايل إلى مواقع الويب إلى أنظمة التشغيل.',
      whatIsEn: 'Software Development is the process of designing, programming, documenting, testing, and maintaining applications, frameworks, or software components.',
      importance: [
        { reason: 'الطلب الهائل', detail: 'نقص في المبرمجين عالميًا - الطلب أكبر من العرض' },
        { reason: 'رواتب مرتفعة', detail: 'من أعلى المهن دخلاً في العالم' },
        { reason: 'حرية العمل', detail: 'يمكنك العمل من أي مكان (Remote / Freelance)' },
        { reason: 'إبداع لا محدود', detail: 'تحويل فكرة إلى منتج يستخدمه ملايين الناس' },
      ],
      applications: ['تطبيقات الويب', 'تطبيقات الموبايل', 'برامج سطح المكتب', 'الألعاب', 'الذكاء الاصطناعي', 'الخدمات الحكومية'],
      careers: [
        { title: 'Frontend Developer', salary: '6k - 15k ج.م', salaryInt: '$60k - $90k' },
        { title: 'Backend Developer', salary: '8k - 18k ج.م', salaryInt: '$70k - $100k' },
        { title: 'Full-Stack Developer', salary: '12k - 25k ج.م', salaryInt: '$80k - $120k' },
        { title: 'Mobile Developer', salary: '12k - 30k ج.م', salaryInt: '$85k - $130k' },
        { title: 'Software Architect', salary: '30k - 60k+ ج.م', salaryInt: '$140k - $200k' },
      ],
      roadmap: [
        { level: 'Beginner', period: '0-6 Months', items: ['HTML + CSS', 'JavaScript Basics', 'Git & GitHub', 'Basic Project (Personal Website)'] },
        { level: 'Foundation', period: '6-12 Months', items: ['React.js / Vue.js', 'Node.js / Python', 'SQL Databases', 'REST APIs'] },
        { level: 'Intermediate', period: '12-18 Months', items: ['TypeScript', 'State Management', 'Testing (Jest)', 'Docker Basics'] },
        { level: 'Advanced', period: '18-24 Months', items: ['Full-Stack Projects', 'CI/CD', 'Cloud Deployment', 'System Design'] },
        { level: 'Professional', period: '24+ Months', items: ['Microservices', 'Performance Optimization', 'Team Leadership', 'Open Source'] },
      ],
    },
    modules: [
      { id: 'web-fund', title: 'Web Development Fundamentals', level: 'مبتدئ', time: '15 ساعة', cert: 'Meta Frontend',
        overviewAr: 'أساسيات تطوير الويب: HTML للهيكل، CSS للتجميل، JavaScript للتفاعل.',
        overviewEn: 'Web Development Fundamentals cover HTML (structure), CSS (presentation), and JavaScript (behavior) - the core technologies of the web.',
        why: 'هذا هو أساس كل شيء في تطوير الويب. بدون إتقان هذه الأساسيات، لا يمكنك التقدم.',
        concepts: ['HTML5 Semantic Tags', 'CSS3 Flexbox & Grid', 'Responsive Design', 'DOM Manipulation', 'ES6+ (Promises, Async/Await)', 'Browser DevTools'],
        tools: ['VS Code', 'Chrome DevTools', 'Git', 'Figma', 'Sass'],
        applications: ['كل موقع ويب تستخدمه يعتمد على HTML/CSS/JS', 'Netflix, YouTube, Google - كلها مبنية على هذه الأساسيات'],
        mistakes: ['إهمال Semantic HTML', 'عدم استخدام Responsive Design', 'كتابة كود JavaScript غير منظم'],
        summary: 'HTML + CSS + JavaScript هي الثالوث المقدس لتطوير الويب.'
      },
      { id: 'frontend', title: 'Frontend Development (React)', level: 'متوسط', time: '20 ساعة', cert: 'Meta Frontend',
        overviewAr: 'تطوير الواجهة الأمامية: بناء واجهات مستخدم تفاعلية باستخدام React.',
        overviewEn: 'Frontend frameworks help developers build complex, interactive user interfaces efficiently using component-based architecture.',
        why: '90% من وظائف Frontend تطلب React أو Angular أو Vue.',
        concepts: ['Components & JSX', 'State & Props', 'Hooks (useState, useEffect)', 'Routing (React Router)', 'State Management (Redux/Zustand)', 'Next.js (SSR)'],
        tools: ['React.js', 'Next.js', 'Redux', 'Tailwind CSS', 'Vite'],
        applications: ['Facebook ← React', 'Twitter/X ← React', 'Alibaba ← Vue.js'],
        mistakes: ['إهمال الـ State Management', 'عدم فهم Virtual DOM', 'كتابة Components ضخمة غير قابلة لإعادة الاستخدام'],
        summary: 'React هو المعيار الذهبي لتطوير الواجهات.'
      },
      { id: 'backend', title: 'Backend Development (Node.js)', level: 'متوسط', time: '20 ساعة', cert: 'AWS Developer',
        overviewAr: 'تطوير الخادم والمنطق الخلفي: معالجة البيانات، APIs، قواعد البيانات.',
        overviewEn: 'Backend Development focuses on server-side logic, database interactions, authentication, and API creation.',
        why: 'أي تطبيق يتعامل مع بيانات يحتاج Backend قوي.',
        concepts: ['REST APIs (GET, POST, PUT, DELETE)', 'JWT & OAuth', 'Middleware', 'Error Handling', 'Database Integration'],
        tools: ['Node.js + Express', 'Python + Django', 'Postman', 'Swagger', 'Nginx'],
        applications: ['Amazon يدير ملايين الطلبات', 'WhatsApp يعالج مليارات الرسائل'],
        mistakes: ['عدم تأمين الـ API', 'إهمال Error Handling', 'عدم استخدام Environment Variables'],
        summary: 'Backend هو مخزن وعقل التطبيق.'
      },
      { id: 'databases', title: 'Databases (SQL & NoSQL)', level: 'مبتدئ-متوسط', time: '12 ساعة', cert: 'None directly',
        overviewAr: 'قواعد البيانات: تخزين وتنظيم واسترجاع البيانات بكفاءة.',
        overviewEn: 'A database is an organized collection of structured information stored electronically.',
        why: 'كل تطبيق يحتاج لتخزين بيانات. كفاءة قاعدة البيانات تؤثر على أداء التطبيق بالكامل.',
        concepts: ['SQL (SELECT, JOIN, GROUP BY)', 'Normalization', 'Indexes', 'Transactions (ACID)', 'MongoDB Documents', 'ORM (Prisma)'],
        tools: ['PostgreSQL', 'MySQL', 'MongoDB', 'Redis', 'DBeaver'],
        applications: ['Instagram يستخدم PostgreSQL + Redis', 'Uber يستخدم MySQL'],
        mistakes: ['N+1 Query Problem', 'عدم استخدام Indexes', 'تجاهل الـ Migrations'],
        summary: 'اختر PostgreSQL للبيانات المنتظمة، MongoDB للمرونة.'
      },
    ],
    glossary: [
      { term: 'Algorithm', arabic: 'خوارزمية', explanation: 'خطوات محددة لحل مشكلة', category: 'أساسيات' },
      { term: 'Variable', arabic: 'متغير', explanation: 'مكان في الذاكرة يخزن قيمة', category: 'أساسيات' },
      { term: 'Function', arabic: 'دالة', explanation: 'قطعة كود تقوم بمهمة محددة', category: 'أساسيات' },
      { term: 'API', arabic: 'واجهة برمجة تطبيقات', explanation: 'وسيلة اتصال بين تطبيقين', category: 'ويب' },
      { term: 'JSON', arabic: 'جيسون', explanation: 'صيغة خفيفة لتبادل البيانات', category: 'ويب' },
      { term: 'Framework', arabic: 'إطار عمل', explanation: 'مجموعة أدوات جاهزة لتسهيل بناء التطبيقات', category: 'أدوات' },
      { term: 'Git', arabic: 'جيت', explanation: 'نظام التحكم في الإصدارات', category: 'أدوات' },
      { term: 'Docker', arabic: 'دوكر', explanation: 'حاويات لتوحيد بيئة التطوير', category: 'أدوات' },
      { term: 'CI/CD', arabic: 'تكامل مستمر', explanation: 'أتمتة اختبار ونشر الكود', category: 'ممارسات' },
      { term: 'React', arabic: 'رياكت', explanation: 'مكتبة لبناء واجهات المستخدم', category: 'أدوات' },
    ],
    tools: [
      { name: 'VS Code', desc: 'محرر أكواد خفيف مع دعم الإضافات', use: 'المحرر الأساسي يوميًا لأي لغة', pros: ['مجاني', 'إضافات لا محدودة', 'Integrated Terminal + Git'], cons: ['قد يكون بطيئًا مع مشاريع ضخمة جدًا'], alt: 'WebStorm, Sublime Text', demand: 'الأعلى استخدامًا' },
      { name: 'React', desc: 'مكتبة لبناء واجهات المستخدم التفاعلية', use: 'تطبيقات SPA وويب ديناميكية', pros: ['مجاني', 'Virtual DOM', 'Hooks', 'مجتمع ضخم'], cons: ['ليس Framework كامل', 'تحتاج لمكتبات إضافية'], alt: 'Angular, Vue.js', demand: 'الأعلى طلبًا' },
      { name: 'Node.js', desc: 'تشغيل JavaScript على الخادم', use: 'بناء APIs وMicroservices', pros: ['سريع', 'JavaScript في كل مكان', 'NPM'], cons: ['Single-threaded', 'Callback Hell (معالج بـ Async/Await)'], alt: 'Python/Django, Java/Spring', demand: 'عالي جدًا' },
      { name: 'Docker', desc: 'حاويات لتوحيد بيئة التطوير والنشر', use: 'كل مشروع Professional', pros: ['بيئة موحدة', 'قابلية نقل', 'مجاني'], cons: ['منحنى تعلم', 'استهلاك موارد'], alt: 'Podman, Vagrant', demand: 'عالي جدًا' },
      { name: 'PostgreSQL', desc: 'قاعدة بيانات علائقية متقدمة', use: 'مشاريع تحتاج ACID واستعلامات معقدة', pros: ['مجاني', 'JSONB', 'PostGIS', 'Full-Text Search'], cons: ['أبطأ من MySQL في بعض الحالات'], alt: 'MySQL, SQLite', demand: 'عالي جدًا' },
      { name: 'Git', desc: 'نظام التحكم في الإصدارات', use: 'كل مشروع - تتبع التغييرات', pros: ['مجاني', 'موزع', 'Branching قوي'], cons: ['منحنى تعلم', 'Conflict Resolution'], alt: 'Mercurial', demand: 'إجباري' },
    ],
    interview: [
      { type: 'hr', q: 'عرفنا عن نفسك', a: 'أنا خريج حاسبات ومعلومات. أكملت تدريب NTI في مسار Software Development وأتقنت React و Node.js. لدي مشاريع على GitHub وأشارك في open source.' },
      { type: 'hr', q: 'لماذا تريد العمل في تطوير البرمجيات؟', a: 'لأنني أحب حل المشكلات والإبداع. البرمجة تسمح لي بتحويل فكرة إلى منتج يستخدمه الناس.' },
      { type: 'technical', q: 'ما الفرق بين == و === في JavaScript؟', a: '== يقارن القيم فقط مع تحويل النوع. === يقارن القيم والنوع معًا. استخدم === دائمًا.', difficulty: 'easy' },
      { type: 'technical', q: 'اشرح Event Loop في JavaScript', a: 'JavaScript Single-threaded. Call Stack ينفذ الأكواد، Web APIs للمهام غير المتزامنة، Callback Queue للانتظار، Event Loop ينقل من Queue لـ Stack عندما يفرغ.', difficulty: 'medium' },
      { type: 'technical', q: 'ما الفرق بين State و Props في React؟', a: 'Props: بيانات تدخل المكون من الخارج (Read-only). State: بيانات داخل المكون يمكن تغييرها وتسبب إعادة رسم.', difficulty: 'easy' },
      { type: 'technical', q: 'اشرح REST API', a: 'GET (قراءة)، POST (إنشاء)، PUT (تحديث)، DELETE (حذف). Stateless - كل طلب مستقل.', difficulty: 'medium' },
      { type: 'scenario', q: 'كيف تحسن أداء تطبيق React بطيء؟', a: '1. React.memo للمكونات\n2. useMemo/useCallback\n3. Code Splitting مع lazy\n4. Virtualization للقوائم الطويلة\n5. Production Build', difficulty: 'hard' },
      { type: 'scenario', q: 'كيف تنشر تطبيق React؟', a: '1. npm run build\n2. اختيار منصة (Vercel, Netlify, AWS S3)\n3. رفع الملفات\n4. إعداد Custom Domain\n5. HTTPS تلقائي', difficulty: 'medium' },
    ],
    career: [
      { level: 'Junior', exp: '0-2 years', title: 'Junior Developer', salary: '5k - 12k ج.م', skills: ['HTML/CSS/JS', 'Git', 'React Basics', 'REST APIs'], certs: ['FreeCodeCamp', 'NTI Certificate'] },
      { level: 'Mid-Level', exp: '2-5 years', title: 'Developer / Engineer', salary: '12k - 25k ج.م', skills: ['React/Vue/Angular', 'Node.js/Django', 'SQL/NoSQL', 'TypeScript'], certs: ['AWS Certified Developer'] },
      { level: 'Senior', exp: '5-8 years', title: 'Senior Engineer', salary: '25k - 45k ج.م', skills: ['System Design', 'Microservices', 'Cloud', 'Mentoring'], certs: ['AWS SA Associate'] },
      { level: 'Lead', exp: '8+ years', title: 'Architect / Tech Lead', salary: '35k - 60k+ ج.م', skills: ['Architecture', 'Team Leadership', 'Strategy'], certs: ['AWS SA Professional'] },
    ],
    revision: {
      keyConcepts: ['HTML (Structure) + CSS (Style) + JS (Behavior)', 'React: Components, Props, State, Hooks', 'REST: GET, POST, PUT, DELETE'],
      importantTerms: ['== vs ===', 'var vs let vs const', 'Promise vs Async/Await', 'SQL vs NoSQL'],
      mustTools: ['VS Code', 'Git/GitHub', 'React/Next.js', 'Node.js', 'PostgreSQL', 'Docker'],
      interviewNuggets: ['اعرف Event Loop', 'تدرب على LeetCode (Easy/Medium)', 'جهز GitHub بمشاريع', 'اعرف System Design Basics'],
    },
  },
  'data-science-ai': {
    intro: {
      title: 'Data Science & AI Track',
      subtitle: 'علوم البيانات والذكاء الاصطناعي',
      whatIs: 'علوم البيانات هي استخراج المعرفة والرؤى من البيانات. الذكاء الاصطناعي هو جعل الآلات تتعلم وتفكر مثل البشر.',
      whatIsEn: 'Data Science combines statistics, mathematics, and programming to extract insights from data. AI enables machines to simulate human intelligence.',
      importance: [
        { reason: 'اتخاذ القرارات', detail: 'Netflix و Amazon تعتمدان على البيانات لكل قرار' },
        { reason: 'توفير التكاليف', detail: 'الصيانة التنبؤية توفر ملايين الدولارات' },
        { reason: 'أتمتة ذكية', detail: 'من السيارات ذاتية القيادة إلى ChatGPT' },
        { reason: 'اكتشاف الأدوية', detail: 'AI يسرع اكتشاف الأدوية الجديدة بنسبة 80%' },
      ],
      applications: ['الصحة (تشخيص الأمراض)', 'المالية (كشف الاحتيال)', 'التجارة (توصيات)', 'النقل (سيارة ذاتية القيادة)', 'التصنيع (صيانة تنبؤية)'],
      careers: [
        { title: 'Data Analyst', salary: '8k - 18k ج.م', salaryInt: '$60k - $85k' },
        { title: 'Data Scientist', salary: '15k - 35k ج.م', salaryInt: '$95k - $140k' },
        { title: 'ML Engineer', salary: '18k - 40k ج.م', salaryInt: '$110k - $160k' },
        { title: 'Data Engineer', salary: '15k - 35k ج.م', salaryInt: '$100k - $150k' },
        { title: 'AI Engineer', salary: '20k - 45k ج.م', salaryInt: '$120k - $170k' },
      ],
      roadmap: [
        { level: 'Beginner', period: '0-6 Months', items: ['Python (NumPy, Pandas)', 'Statistics & Probability', 'SQL', 'Data Visualization'] },
        { level: 'Foundation', period: '6-12 Months', items: ['Machine Learning (Scikit-learn)', 'Supervised Learning', 'Unsupervised Learning', 'Feature Engineering'] },
        { level: 'Intermediate', period: '12-18 Months', items: ['Deep Learning', 'Neural Networks', 'TensorFlow / PyTorch', 'Computer Vision'] },
        { level: 'Advanced', period: '18-24 Months', items: ['NLP (Transformers, BERT)', 'MLOps', 'Big Data (Spark)', 'Deployment'] },
        { level: 'Professional', period: '24+ Months', items: ['LLMs & RAG', 'ML Research', 'AI Architecture', 'Team Leadership'] },
      ],
    },
    modules: [
      { id: 'python-ds', title: 'Python for Data Science', level: 'مبتدئ', time: '15 ساعة', cert: 'None',
        overviewAr: 'استخدام Python لتحليل البيانات ومعالجتها باستخدام Pandas و NumPy.',
        overviewEn: 'Python with Pandas and NumPy for data manipulation, cleaning, and analysis.',
        why: 'Python هي اللغة الأولى في عالم البيانات.', concepts: ['NumPy Arrays', 'Pandas DataFrames', 'Data Cleaning', 'Matplotlib/Seaborn'], tools: ['Jupyter', 'Pandas', 'NumPy', 'Matplotlib'], applications: ['تحليل مبيعات شركة', 'تنظيف بيانات العملاء'], mistakes: ['عدم معالجة القيم المفقودة', 'إهمال تحليل البيانات الاستكشافي'], summary: 'Python + Pandas = أساس كل مشروع DS' },
      { id: 'ml', title: 'Machine Learning', level: 'متوسط', time: '20 ساعة', cert: 'TensorFlow',
        overviewAr: 'بناء نماذج تتعلم من البيانات للتنبؤ والتصنيف.', overviewEn: 'Building models that learn from data to make predictions and decisions.', why: 'ML هو قلب Data Science.', concepts: ['Regression', 'Classification', 'Decision Trees', 'Random Forest', 'XGBoost', 'Overfitting'], tools: ['Scikit-learn', 'XGBoost', 'Optuna'], applications: ['توقع سعر البيت', 'تصنيف Spam'], mistakes: ['Overfitting', 'تجاهل Feature Engineering'], summary: 'ML يحول البيانات إلى تنبؤات.' },
      { id: 'dl', title: 'Deep Learning & Neural Networks', level: 'متقدم', time: '20 ساعة', cert: 'TensorFlow',
        overviewAr: 'الشبكات العصبية العميقة: نماذج معقدة تحاكي عمل الدماغ.', overviewEn: 'Deep Neural Networks simulate the human brain to solve complex problems.', why: 'DL أساس كل تقنيات AI الحديثة.', concepts: ['Neural Networks', 'CNN (Images)', 'RNN/LSTM (Text)', 'Transformers (GPT)', 'Transfer Learning'], tools: ['TensorFlow', 'PyTorch', 'Hugging Face'], applications: ['ChatGPT', 'Tesla Autopilot', 'Google Photos'], mistakes: ['عدم كفاية البيانات', 'Learning Rate خاطئ', 'تجاهل Overfitting'], summary: 'DL هو مستقبل AI.' },
    ],
    glossary: [
      { term: 'Machine Learning', arabic: 'تعلم آلي', explanation: 'نماذج تتعلم من البيانات بدون برمجة صريحة', category: 'أساسيات' },
      { term: 'Deep Learning', arabic: 'تعلم عميق', explanation: 'شبكات عصبية متعددة الطبقات', category: 'أساسيات' },
      { term: 'Overfitting', arabic: 'فرط التخصيص', explanation: 'النموذج يحفظ البيانات بدلاً من تعلم الأنماط', category: 'مشاكل' },
      { term: 'NLP', arabic: 'معالجة لغة طبيعية', explanation: 'تحليل وفهم النصوص البشرية', category: 'تخصصات' },
      { term: 'Computer Vision', arabic: 'رؤية حاسوبية', explanation: 'تحليل الصور والفيديو', category: 'تخصصات' },
      { term: 'Transformer', arabic: 'محول', explanation: 'أحدث بنية في NLP (أساس GPT)', category: 'تقنيات' },
    ],
    tools: [
      { name: 'Pandas', desc: 'معالجة وتحليل البيانات الجدولية', use: 'كل مشروع DS', pros: ['قوي جدًا', 'سهل', 'مجاني'], cons: ['بطيء مع بيانات ضخمة جدًا'], alt: 'Polars, Dask', demand: 'إجباري' },
      { name: 'Scikit-learn', desc: 'خوارزميات ML التقليدية', use: 'التصنيف والانحدار والتجميع', pros: ['سهل', 'متكامل', 'ممتاز للتعلم'], cons: ['ليس للـ Deep Learning'], alt: 'XGBoost, LightGBM', demand: 'إجباري' },
      { name: 'TensorFlow/PyTorch', desc: 'أطر العمل للتعلم العميق', use: 'الشبكات العصبية', pros: ['قوي جدًا', 'GPU acceleration'], cons: ['منحنى تعلم حاد'], alt: 'JAX, Keras', demand: 'عالي جدًا' },
    ],
    interview: [
      { type: 'hr', q: 'لماذا Data Science؟', a: 'I love finding patterns in data and using them to solve real problems.' },
      { type: 'technical', q: 'ما هو Overfitting وكيف تمنعه؟', a: 'النموذج يحفظ البيانات بدلاً من أن يتعلم. الحلول: Cross-validation, Regularization, More data, Early Stopping.', difficulty: 'medium' },
      { type: 'technical', q: 'اشرح Bias-Variance Tradeoff', a: 'High Bias = نموذج بسيط (Underfitting). High Variance = نموذج معقد (Overfitting). الهدف هو التوازن.', difficulty: 'medium' },
      { type: 'scenario', q: 'كيف تبني نظام توصيات؟', a: '1. Collaborative Filtering\n2. Content-Based\n3. Hybrid\n4. A/B Testing', difficulty: 'hard' },
    ],
    career: [
      { level: 'Junior', exp: '0-2', title: 'Data Analyst / Jr. Data Scientist', salary: '6k - 14k ج.م', skills: ['Python', 'SQL', 'Statistics', 'Pandas'], certs: ['Google Data Analytics'] },
      { level: 'Mid-Level', exp: '2-5', title: 'Data Scientist / ML Engineer', salary: '15k - 30k ج.م', skills: ['Scikit-learn', 'DL', 'Cloud ML'], certs: ['TensorFlow Developer'] },
      { level: 'Senior', exp: '5-8', title: 'Senior Data Scientist', salary: '30k - 50k ج.م', skills: ['MLOps', 'Architecture', 'NLP/CV'], certs: ['AWS ML Specialty'] },
      { level: 'Lead', exp: '8+', title: 'Principal Scientist / AI Lead', salary: '45k - 70k+ ج.م', skills: ['Research', 'Strategy', 'Leadership'], certs: ['PhD preferred'] },
    ],
    revision: {
      keyConcepts: ['DS Pipeline: Business → Data → Clean → Model → Evaluate → Deploy', 'Supervised vs Unsupervised', 'CNN for Images, RNN/Transformer for Text'],
      importantTerms: ['Overfitting vs Underfitting', 'Precision vs Recall', 'Bias vs Variance'],
      mustTools: ['Python + Pandas', 'Scikit-learn', 'TensorFlow/PyTorch', 'Jupyter'],
      interviewNuggets: ['اعرف Bias-Variance', 'جهز مشروع كامل', 'SQL أساسي', 'Statistics أساسي'],
    },
  },
  'cloud-computing': {
    intro: {
      title: 'Cloud Computing Track',
      subtitle: 'الحوسبة السحابية',
      whatIs: 'بدلاً من شراء خوادم باهظة الثمن، تستأجر خوادم وخدمات من AWS أو Azure أو Google. تدفع فقط على حسب استخدامك.',
      whatIsEn: 'Cloud computing is the on-demand delivery of IT resources over the internet with pay-as-you-go pricing.',
      importance: [
        { reason: 'توفير التكاليف', detail: 'لا تشتري خوادم - استأجر فقط ما تحتاج' },
        { reason: 'سرعة التوسع', detail: 'أضف 1000 خادم في دقائق' },
        { reason: 'التوفر العالي', detail: 'خدماتك متاحة 99.99% من الوقت' },
        { reason: 'الأمان', detail: 'مزودو السحابة يستثمرون مليارات في الأمن' },
      ],
      applications: ['استضافة المواقع', 'تخزين الملفات', 'قواعد البيانات', 'AI/ML', 'IoT'],
      careers: [
        { title: 'Cloud Engineer', salary: '12k - 30k ج.م', salaryInt: '$80k - $130k' },
        { title: 'DevOps Engineer', salary: '15k - 35k ج.م', salaryInt: '$100k - $150k' },
        { title: 'Cloud Architect', salary: '30k - 60k+ ج.م', salaryInt: '$140k - $200k' },
        { title: 'SRE', salary: '20k - 45k ج.م', salaryInt: '$120k - $170k' },
      ],
      roadmap: [
        { level: 'Beginner', period: '0-3 Months', items: ['Linux Basics', 'Networking', 'AWS Free Tier', 'EC2, S3, IAM'] },
        { level: 'Foundation', period: '3-6 Months', items: ['AWS Services (VPC, RDS, Lambda)', 'Cloud Practitioner Cert'] },
        { level: 'Intermediate', period: '6-12 Months', items: ['Docker', 'Terraform', 'CI/CD', 'AWS SA Associate'] },
        { level: 'Advanced', period: '12-18 Months', items: ['Kubernetes', 'Microservices', 'Multi-Cloud', 'AWS SA Professional'] },
        { level: 'Professional', period: '18+ Months', items: ['Cloud Architecture', 'Cost Optimization', 'Migration Strategies'] },
      ],
    },
    modules: [],
    glossary: [
      { term: 'Cloud Computing', arabic: 'حوسبة سحابية', explanation: 'تقديم خدمات تقنية عبر الإنترنت', category: 'أساسيات' },
      { term: 'IaaS', arabic: 'بنية تحتية كخدمة', explanation: 'خوادم افتراضية وشبكات (EC2)', category: 'نماذج' },
      { term: 'PaaS', arabic: 'منصة كخدمة', explanation: 'منصة تطوير بدون إدارة خوادم', category: 'نماذج' },
      { term: 'SaaS', arabic: 'برنامج كخدمة', explanation: 'تطبيقات جاهزة (Gmail)', category: 'نماذج' },
      { term: 'EC2', arabic: 'حوسبة مرنة', explanation: 'خوادم افتراضية في AWS', category: 'AWS' },
      { term: 'S3', arabic: 'تخزين بسيط', explanation: 'تخزين ملفات غير محدود', category: 'AWS' },
      { term: 'Lambda', arabic: 'لامبدا', explanation: 'كود بدون خادم - يشتغل عند الطلب', category: 'AWS' },
      { term: 'Docker', arabic: 'حاوية', explanation: 'حزم التطبيق في حاوية', category: 'أدوات' },
      { term: 'Kubernetes', arabic: 'كوبرنيتس', explanation: 'إدارة آلاف الحاويات', category: 'أدوات' },
      { term: 'Terraform', arabic: 'تيرافورم', explanation: 'بنية تحتية ككود', category: 'أدوات' },
    ],
    tools: [
      { name: 'AWS', desc: 'أكبر مزود خدمات سحابية', use: 'كل شيء: خوادم، تخزين، AI', pros: ['الأوسع', 'أكثر الخدمات', 'Free Tier سخي'], cons: ['معقد (200+ خدمة)', 'مكلف إذا لم تراقب'], alt: 'Azure, GCP', demand: 'الأعلى' },
      { name: 'Terraform', desc: 'IaC متعدد السحابات', use: 'إدارة البنية التحتية ككود', pros: ['متعدد السحابات', 'HCL سهل', 'State Management'], cons: ['منحنى تعلم', 'State file security'], alt: 'CloudFormation, Pulumi', demand: 'عالي جدًا' },
      { name: 'Docker', desc: 'حاويات خفيفة', use: 'توحيد بيئة التطوير والنشر', pros: ['خفيف', 'Portable', 'مجتمع ضخم'], cons: ['أمان الحاويات', 'شبكات معقدة'], alt: 'Podman', demand: 'إجباري' },
      { name: 'Kubernetes', desc: 'تنسيق الحاويات', use: 'إدارة آلاف الحاويات تلقائيًا', pros: ['Auto-scaling', 'Self-healing', 'CNCF'], cons: ['معقد جدًا', 'منحنى تعلم حاد'], alt: 'Docker Swarm, Nomad', demand: 'عالي جدًا' },
    ],
    interview: [
      { type: 'hr', q: 'لماذا الحوسبة السحابية؟', a: 'لأنها مستقبل البنية التحتية. كل الشركات تنتقل للسحابة.' },
      { type: 'technical', q: 'EC2 vs Lambda?', a: 'EC2: خادم يعمل 24/7. Lambda: كود يشتغل عند الطلب فقط (أرخص).', difficulty: 'easy' },
      { type: 'technical', q: 'What is an S3 Bucket?', a: 'Container لتخزين الملفات. غير محدود، رخيص، متوفر من أي مكان.', difficulty: 'easy' },
      { type: 'technical', q: 'Explain Shared Responsibility Model', a: 'AWS يؤمن السحابة نفسها. أنت تؤمن ما في السحابة (بياناتك، إعدادات IAM).', difficulty: 'medium' },
    ],
    career: [
      { level: 'Junior', exp: '0-2', title: 'Cloud Support / Jr. Cloud Engineer', salary: '8k - 16k ج.م', skills: ['Linux', 'Networking', 'AWS Basics'], certs: ['AWS CCP'] },
      { level: 'Mid-Level', exp: '2-5', title: 'Cloud Engineer / DevOps', salary: '16k - 30k ج.م', skills: ['Terraform', 'Docker', 'CI/CD'], certs: ['AWS SAA'] },
      { level: 'Senior', exp: '5-8', title: 'Senior Cloud Architect', salary: '30k - 55k ج.م', skills: ['K8s', 'Multi-Cloud', 'Cost Optimization'], certs: ['AWS SAP'] },
      { level: 'Lead', exp: '8+', title: 'Principal Architect', salary: '45k - 80k+ ج.م', skills: ['Enterprise Strategy', 'Migration'], certs: ['All AWS Professional'] },
    ],
    revision: {
      keyConcepts: ['IaaS / PaaS / SaaS', 'Public / Private / Hybrid / Multi-Cloud', 'Region / Availability Zone'],
      importantTerms: ['EC2 (Compute)', 'S3 (Storage)', 'Lambda (Serverless)', 'VPC (Network)', 'IAM (Security)'],
      mustTools: ['AWS Console/CLI', 'Terraform', 'Docker', 'GitHub Actions'],
      interviewNuggets: ['اعرف EC2 vs Lambda', 'S3 Storage Classes', 'Well-Architected Framework'],
    },
  },
  'systems-administration': {
    intro: {
      title: 'Systems Administration Track',
      subtitle: 'إدارة الأنظمة',
      whatIs: 'إدارة الأنظمة هي عملية إدارة وصيانة وتشغيل أنظمة الحاسوب والخوادم والشبكات في المؤسسات. تشمل تثبيت وتكوين أنظمة التشغيل (Linux, Windows Server)، إدارة المستخدمين والصلاحيات، مراقبة الأداء، تطبيق سياسات الأمان، النسخ الاحتياطي، واستكشاف الأخطاء وإصلاحها لضمان توفر الخدمات بشكل مستمر وفعال.',
      whatIsEn: 'Systems administration is the process of managing, maintaining, and operating computer systems, servers, and networks within organizations. It includes installing and configuring operating systems (Linux, Windows Server), managing users and permissions, monitoring performance, applying security policies, backup and recovery, and troubleshooting to ensure continuous and efficient availability of services.',
      importance: [
        { reason: 'ضمان استمرارية الأعمال', detail: 'Systems administrators ensure that servers and critical services remain operational 24/7, minimizing downtime that could cost organizations millions.' },
        { reason: 'أمن المعلومات وحماية البيانات', detail: 'يطبق مسؤولو الأنظمة سياسات الأمان والتحديثات الأمنية وجدران الحماية لحماية البيانات من الاختراقات والهجمات الإلكترونية.' },
        { reason: 'إدارة الموارد بكفاءة', detail: 'Optimizing server resources, storage, and network bandwidth to ensure peak performance while reducing operational costs.' },
        { reason: 'دعم البنية التحتية للتطبيقات', detail: 'توفير البيئة المناسبة لتشغيل التطبيقات والخدمات مثل قواعد البيانات وخوادم الويب والبريد الإلكتروني.' },
      ],
      applications: ['Linux Server Administration (Ubuntu, RHEL, CentOS)', 'Windows Server & Active Directory Management', 'Network Services (DNS, DHCP, TCP/IP, VPN)', 'Virtualization & Cloud Infrastructure (VMware, Hyper-V, AWS)', 'Backup & Disaster Recovery Solutions'],
      careers: [
        { title: 'Junior Systems Administrator', salary: '6k - 10k ج.م', salaryInt: '$60k - $80k' },
        { title: 'Systems Administrator', salary: '10k - 18k ج.م', salaryInt: '$75k - $100k' },
        { title: 'Senior Systems Administrator', salary: '18k - 30k ج.م', salaryInt: '$100k - $130k' },
        { title: 'DevOps Engineer', salary: '22k - 40k ج.م', salaryInt: '$120k - $160k' },
        { title: 'IT Infrastructure Manager', salary: '30k - 50k ج.م', salaryInt: '$140k - $190k' },
      ],
      roadmap: [
        { level: 'Beginner', period: '0-6 Months', items: ['Networking Basics (OSI, TCP/IP)', 'Linux CLI & File System', 'Windows Server Basics', 'Shell Scripting (Bash)'] },
        { level: 'Foundation', period: '6-12 Months', items: ['Linux Administration (User Mgmt, Services)', 'Windows Server (AD, DNS, DHCP)', 'Virtualization (VMware, Hyper-V)', 'Monitoring (Nagios, Zabbix)'] },
        { level: 'Intermediate', period: '12-18 Months', items: ['Active Directory & Group Policy', 'Storage Management (RAID, SAN)', 'Automation (Ansible, PowerShell)', 'Cloud Fundamentals (AWS/Azure)'] },
        { level: 'Advanced', period: '18-24 Months', items: ['Configuration Management (Puppet, Chef)', 'Containerization (Docker, K8s)', 'Security Hardening', 'ITIL Service Management'] },
        { level: 'Professional', period: '24+ Months', items: ['Cloud Architecture', 'Enterprise Infrastructure Design', 'CI/CD Pipelines', 'SRE & Leadership'] },
      ],
    },
    modules: [
      { id: 'linux-admin', title: 'Linux System Administration', level: 'متوسط', time: '40 ساعة', cert: 'LFCS',
        overviewAr: 'أساسيات إدارة أنظمة لينكس: المستخدمين والصلاحيات، الحزم والخدمات، مراقبة النظام، الشبكات وإعداد خوادم الويب.',
        overviewEn: 'Linux powers over 90% of servers worldwide. This module covers user management, permissions, packages, services, monitoring, networking, and web servers.',
        why: 'Linux هو العمود الفقري للبنية التحتية الحديثة. 90% من الخوادم تعمل عليه.',
        concepts: ['User & Group Management', 'File Permissions (chmod, chown)', 'Package Management (apt, yum)', 'Systemd & Service Management', 'Process Monitoring'],
        tools: ['Ubuntu Server', 'RHEL/CentOS', 'Bash', 'Vim', 'htop / iostat'],
        applications: ['Configuring Apache/Nginx Web Servers', 'Setting up MariaDB/PostgreSQL', 'Automating backups with cron'],
        mistakes: ['تجاهل السجلات عند استكشاف الأخطاء', 'تشغيل أوامر دون فهم التأثير', 'إهمال التحديثات الأمنية'],
        summary: 'Linux administration is the foundation of modern IT infrastructure. Master it to manage any server environment.' },
      { id: 'windows-server', title: 'Windows Server & Active Directory', level: 'متوسط', time: '45 ساعة', cert: 'Microsoft Windows Server',
        overviewAr: 'إدارة Windows Server: Active Directory، Group Policy، DNS، DHCP، وإدارة الموارد.',
        overviewEn: 'Active Directory is the de facto standard for identity management. This module covers AD setup, GPO, DNS, DHCP, and Hyper-V.',
        why: 'معظم الشركات تعمل ببيئات هايبرد. Active Directory أساسي لإدارة الهوية.',
        concepts: ['AD Domain Services', 'Group Policy Objects (GPO)', 'DNS & DHCP on Windows', 'Hyper-V Virtualization', 'WSUS'],
        tools: ['Windows Server 2022', 'AD Users & Computers', 'GPMC', 'PowerShell', 'Windows Admin Center'],
        applications: ['Managing domain users and OUs', 'Implementing security policies via GPO', 'Deploying apps via Group Policy'],
        mistakes: ['منح صلاحيات مفرطة', 'عدم إنشاء هيكل OUs مناسب', 'إهمال نسخ AD الاحتياطي'],
        summary: 'Windows Server and AD are at the heart of enterprise IT. Hands-on experience is essential for any sysadmin.' },
      { id: 'network-admin', title: 'Network Administration & Services', level: 'أساسي', time: '35 ساعة', cert: 'CompTIA Network+',
        overviewAr: 'أساسيات الشبكات: TCP/IP، Subnetting، DNS، DHCP، جدران الحماية، واستكشاف المشاكل.',
        overviewEn: 'Networking is the circulatory system of IT. Covers TCP/IP, subnetting, DNS/DHCP config, firewalls, and troubleshooting.',
        why: 'بدون فهم الشبكات، لا يمكن تشخيص مشاكل البنية التحتية أو تصميمها.',
        concepts: ['OSI & TCP/IP Models', 'IPv4/IPv6 Subnetting', 'DNS Zone Management', 'DHCP Lease Process', 'NAT & Port Forwarding'],
        tools: ['Wireshark', 'tcpdump', 'Bind9', 'iptables / firewalld', 'Cisco Packet Tracer'],
        applications: ['Corporate DNS server with forward/reverse zones', 'DHCP server with reservations', 'Firewall rules for DMZ'],
        mistakes: ['تقسيم شبكي خاطئ', 'فتح منافذ جدار ناري غير ضرورية', 'عدم إعداد تكرار DNS'],
        summary: 'Network administration is core for every sysadmin. Build a strong foundation in networking.' },
      { id: 'automation', title: 'Automation & Monitoring', level: 'متقدم', time: '40 ساعة', cert: 'RHCE / Prometheus Certified',
        overviewAr: 'أتمتة المهام باستخدام Ansible و PowerShell، ومراقبة البنية التحتية باستخدام Prometheus و Grafana.',
        overviewEn: 'Automation separates junior sysadmins from seniors. Covers Ansible, PowerShell, Prometheus, Grafana, and ELK stack.',
        why: 'الإدارة اليدوية لا تتوسع. الأتمتة تقلل الأخطاء وتوفر الوقت.',
        concepts: ['Infrastructure as Code (IaC)', 'Ansible Playbooks', 'Idempotency', 'Prometheus Metrics & Alerting', 'Log Aggregation'],
        tools: ['Ansible', 'PowerShell', 'Prometheus & Grafana', 'Nagios / Zabbix', 'ELK Stack'],
        applications: ['Server provisioning with Ansible', 'Prometheus exporters for monitoring', 'Grafana dashboards for metrics'],
        mistakes: ['كتابة سكريبتات غير Idempotent', 'إرهاق التنبيهات', 'عدم اختبار الأتمتة في بيئة اختبار'],
        summary: 'Automation and monitoring enable managing infrastructure at scale with modern IaC and observability tools.' },
      { id: 'backup-dr', title: 'Backup & Disaster Recovery', level: 'متوسط', time: '25 ساعة', cert: 'ITIL Foundation',
        overviewAr: 'استراتيجيات النسخ الاحتياطي واستعادة الكوارث: 3-2-1، RPO/RTO، Veeam، وإدارة الشهادات.',
        overviewEn: 'Data loss is existential. Covers 3-2-1 backup strategy, RPO/RTO, disaster recovery planning, and ITIL.',
        why: 'فقدان البيانات كارثة. مسؤول النظام يضمن استمرارية الأعمال.',
        concepts: ['3-2-1 Backup Strategy', 'RPO & RTO', 'DR vs Business Continuity', 'SSL/TLS Certificate Management', 'ITIL Lifecycle'],
        tools: ['Veeam Backup', 'rsync / tar / duplicity', 'Acronis', 'OpenSSL', 'ServiceNow'],
        applications: ['Encrypted backups to offsite storage', 'Disaster recovery runbook', 'Certificate auto-renewal with Let\'s Encrypt'],
        mistakes: ['عدم اختبار النسخ الاحتياطي', 'تخزين النسخ في نفس الموقع', 'استخدام شهادات SSL منتهية الصلاحية'],
        summary: 'Security and disaster recovery are critical. Protect data, ensure recoverability, and align with ITIL standards.' },
    ],
    glossary: [
      { term: 'Active Directory', arabic: 'الدليل النشط', explanation: 'خدمة دليل من Microsoft تدير المصادقة والصلاحيات للمستخدمين على شبكات Windows.', category: 'Identity' },
      { term: 'DNS', arabic: 'نظام أسماء النطاقات', explanation: 'يترجم أسماء النطاقات (google.com) إلى عناوين IP.', category: 'Networking' },
      { term: 'DHCP', arabic: 'بروتوكول التكوين الديناميكي', explanation: 'يوزع عناوين IP تلقائياً للأجهزة على الشبكة.', category: 'Networking' },
      { term: 'Hypervisor', arabic: 'المشرف الافتراضي', explanation: 'برنامج يسمح بتشغيل أنظمة تشغيل افتراضية على جهاز واحد (VMware ESXi).', category: 'Virtualization' },
      { term: 'RAID', arabic: 'مصفوفة الأقراص', explanation: 'تقنية تجمع أقراص صلبة لتحسين الأداء أو توفير تكرار البيانات.', category: 'Storage' },
      { term: 'Ansible', arabic: 'أنسبل', explanation: 'أداة أتمتة لإدارة تكوين الخوادم بدون تثبيت وكيل.', category: 'Automation' },
      { term: 'SELinux', arabic: 'سيلينوكس', explanation: 'نظام أمان في نواة لينكس للتحكم الدقيق في صلاحيات العمليات.', category: 'Security' },
      { term: 'iptables', arabic: 'آي بي تيبلز', explanation: 'أداة جدار حماية في لينكس لتصفية حزم الشبكة.', category: 'Networking' },
      { term: 'LDAP', arabic: 'بروتوكول LDAP', explanation: 'بروتوكول للوصول لخدمات الدليل والاستعلام عن المستخدمين.', category: 'Identity' },
      { term: 'vSphere vMotion', arabic: 'في موشن', explanation: 'تقنية VMware لنقل آلة افتراضية بين مضيفين بدون توقف الخدمة.', category: 'Virtualization' },
      { term: 'RPO', arabic: 'هدف نقطة الاسترداد', explanation: 'أقصى فترة زمنية مقبولة لفقدان البيانات أثناء الكارثة.', category: 'Backup' },
      { term: 'ITIL', arabic: 'آي تي آي إل', explanation: 'إطار عمل لأفضل ممارسات إدارة خدمات تقنية المعلومات.', category: 'Management' },
      { term: 'Prometheus', arabic: 'بروميثيوس', explanation: 'نظام مراقبة مفتوح المصدر يجمع المقاييس والتنبيهات.', category: 'Monitoring' },
      { term: 'Container', arabic: 'حاوية', explanation: 'تغليف التطبيق مع تبعياته لتشغيل متناسق عبر البيئات (Docker).', category: 'Virtualization' },
      { term: 'PowerShell', arabic: 'باورشيل', explanation: 'لغة سكربتات من Microsoft لإدارة أتمتة أنظمة Windows.', category: 'Automation' },
    ],
    tools: [
      { name: 'Ansible', desc: 'أداة أتمتة مفتوحة المصدر لإدارة التهيئة ونشر التطبيقات', use: 'إدارة تكوين الخوادم وأتمتة المهام بدون تثبيت وكيل', pros: ['Agentless (SSH)', 'YAML سهلة', 'مكتبات جاهزة ضخمة'], cons: ['أبطأ من Puppet في البيئات الكبيرة'], alt: 'Puppet, Chef, SaltStack', demand: 'عالي جداً' },
      { name: 'VMware vSphere', desc: 'منصة المحاكاة الافتراضية الرائدة في المؤسسات', use: 'إنشاء وإدارة VMs وتجميع الموارد', pros: ['استقرار عالي', 'vMotion, HA, DRS', 'توافق واسع'], cons: ['تكلفة ترخيص مرتفعة'], alt: 'Hyper-V, Proxmox, KVM', demand: 'مرتفع' },
      { name: 'Prometheus + Grafana', desc: 'نظام مراقبة وتنبيه مفتوح المصدر مع لوحات معلومات', use: 'جمع المقاييس والتنبيه وعرض البيانات', pros: ['PromQL قوي', 'تكامل K8s', 'Grafana تصور احترافي'], cons: ['ليس HA بمفرده', 'تخزين طويل الأجل معقد'], alt: 'Zabbix, Nagios, Datadog', demand: 'عالي جداً' },
      { name: 'PowerShell', desc: 'لغة سكربتات من Microsoft لإدارة Windows', use: 'إدارة AD وأتمتة مهام Windows وAzure', pros: ['تكامل عميق مع Microsoft', 'إدارة عن بعد'], cons: ['يعمل فقط على Windows'], alt: 'Bash, Python', demand: 'مرتفع' },
      { name: 'Veeam Backup', desc: 'حل نسخ احتياطي للبيئات الافتراضية', use: 'Backup VMs واستعادة الملفات والتطبيقات', pros: ['استعادة على مستوى الملف', 'SureBackup للاختبار', 'تكامل VMware/Hyper-V'], cons: ['ترخيص تجاري مكلف'], alt: 'Acronis, Commvault', demand: 'مرتفع' },
    ],
    interview: [
      { type: 'hr', q: 'عرفنا عن نفسك ولماذا اخترت إدارة الأنظمة؟', a: 'أنا خريج حاسبات ومعلومات وأكملت تدريب NTI في مسار Systems Administration. اخترت هذا المجال لأنني أستمتع ببناء وصيانة البنية التحتية لتكنولوجيا المعلومات التي تدعم تشغيل المؤسسات.' },
      { type: 'hr', q: 'كيف تتعامل مع الضغط أثناء أعطال النظام؟', a: 'أظل هادئاً وأتبع عملية استجابة منظمة: تقييم التأثير، تحديد السبب الجذري، التواصل مع أصحاب المصلحة، ثم توثيق كل شيء وعمل post-mortem.' },
      { type: 'technical', q: 'اشرح مراحل إقلاع Linux.', a: '1) BIOS/UEFI يعمل POST، 2) Boot loader (GRUB2) يحمل النواة، 3) Kernel يحمل initramfs، 4) Kernel يهيئ الأجهزة ويحمل root filesystem، 5) systemd يصبح PID 1 ويبدأ الخدمات.', difficulty: 'medium' },
      { type: 'technical', q: 'الفرق بين Soft Link و Hard Link في Linux؟', a: 'Hard Link يشير لنفس inode على القرص، لا يتأثر بحذف الملف الأصلي. Soft Link ملف خاص يشير لمسار الملف، لو اتلغى الملف الأصلي يتكسر Soft Link. Soft Link يقدر يعبر boundaries filesystem، Hard Link لا.', difficulty: 'easy' },
      { type: 'technical', q: 'كيف تعمل replication في Active Directory؟', a: 'AD يستخدم Multi-Master Replication. KCC ينشئ Ring Topology. التغييرات تنتقل عبر RPC. الفاصل الزمني داخل الموقع 15 دقيقة، بين المواقع 180 دقيقة. التغييرات العاجلة (مثل تغيير كلمة المرور) تنتقل فوراً.', difficulty: 'medium' },
      { type: 'scenario', q: 'سيرفر حرج يعمل بـ 100% CPU والخدمات مش عشانة. اشرح خطوات التشخيص.', a: '1) SSH عالسيرفر. 2) تشغيل top/htop لتحديد العملية. 3) التأكد لو عملية معروفة ولا اختراق. 4) قتل العملية لاستعادة الخدمات فوراً. 5) فحص السجلات (/var/log/syslog). 6) تطبيق الإصلاح. 7) توثيق الحادثة.', difficulty: 'hard' },
      { type: 'scenario', q: 'مطلوب ترحيل الشركة من Exchange محلي لـ Microsoft 365. كيف تخطط؟', a: '1) تقييم البيئة الحالية. 2) اختيار طريقة الترحيل (Cutover, Staged, Hybrid). 3) تحديث Exchange المحلي. 4) تشغيل IdFix. 5) إعداد Azure AD Connect. 6) ترحيل تجريبي. 7) ترحيل مجموعات المستخدمين. 8) التحقق من تدفق البريد. 9) إيقاف التشغيل بعد الاستقرار.', difficulty: 'hard' },
    ],
    career: [
      { level: 'Junior', exp: '0-2 years', title: 'Jr. Systems Administrator', salary: '6k - 10k ج.م', skills: ['Linux/Windows Basics', 'User Management', 'Networking Basics', 'Shell Scripting'], certs: ['CompTIA A+'] },
      { level: 'Mid-Level', exp: '2-5 years', title: 'Systems Administrator', salary: '12k - 22k ج.م', skills: ['Adv. Linux/Windows', 'Active Directory', 'VMware/Hyper-V', 'Ansible'], certs: ['LFCS', 'VMware VCP'] },
      { level: 'Senior', exp: '5-8 years', title: 'Senior SysAdmin', salary: '22k - 35k ج.م', skills: ['Infrastructure Design', 'Monitoring', 'Security', 'Cloud (AWS/Azure)'], certs: ['RHCE', 'AWS SAA'] },
      { level: 'Lead', exp: '8+ years', title: 'IT Infrastructure Manager', salary: '35k - 55k ج.م', skills: ['Team Leadership', 'Strategic Planning', 'Budget & Vendor Mgmt'], certs: ['AWS SAP', 'PMP', 'CISSP'] },
    ],
    revision: {
      keyConcepts: ['User & Permission Management', 'TCP/IP Stack & Subnetting', '3-2-1 Backup Strategy (RPO, RTO)', 'Infrastructure as Code with Ansible'],
      importantTerms: ['Active Directory', 'DNS/DHCP', 'Hypervisor', 'RAID', 'SELinux', 'ITIL', 'RPO/RTO', 'vMotion'],
      mustTools: ['Linux CLI (bash, grep, awk)', 'Ansible', 'VMware vSphere', 'Prometheus + Grafana', 'Wireshark'],
      interviewNuggets: ['اشرح Linux Boot Process', 'احفظ 3-2-1 Backup Rule', 'افهم AD Replication', 'جهز سيناريوهات استكشاف الأعطال'],
    },
  },
  'electronics': {
    intro: {
      title: 'Electronics & Embedded Systems Track',
      subtitle: 'الإلكترونيات والأنظمة المدمجة',
      whatIs: 'الإلكترونيات والأنظمة المدمجة هو مجال يجمع بين تصميم الدوائر الإلكترونية وبرمجة المتحكمات الدقيقة لتطوير أنظمة ذكية. يشمل فهم المكونات الإلكترونية، تحليل الإشارات، برمجة Firmware بلغة C/C++، تصميم لوحات PCB، وتطبيق بروتوكولات الاتصال IoT.',
      whatIsEn: 'Electronics & Embedded Systems combines circuit design with microcontroller programming for intelligent systems. Covers components, signal analysis, C/C++ firmware, PCB design, and IoT protocols.',
      importance: [
        { reason: 'الثورة الصناعية الرابعة', detail: 'جميع أجهزة IoT والصناعة 4.0 تعتمد على الأنظمة المدمجة' },
        { reason: 'الطلب العالمي المتزايد', detail: 'سوق الأنظمة المدمجة يتجاوز 130 مليار دولار مع نقص حاد في المهندسين' },
        { reason: 'تأثير ملموس', detail: 'ترى نتائج عملك في أجهزة حقيقية: سيارات، درونات، أجهزة طبية' },
        { reason: 'تنوع مجالات العمل', detail: 'السيارات الذكية، الأجهزة الطبية، الطيران، الإلكترونيات الاستهلاكية' },
      ],
      applications: ['السيارات الذكية وأنظمة ECU', 'الأجهزة الطبية (مراقبة القلب، التنفس)', 'أنظمة المنازل الذكية (Smart Home)', 'الطائرات بدون طيار (Drones)', 'الأجهزة القابلة للارتداء (Wearables)'],
      careers: [
        { title: 'Embedded Systems Engineer', salary: '8k - 18k ج.م', salaryInt: '$70k - $100k' },
        { title: 'Firmware Engineer', salary: '9k - 20k ج.م', salaryInt: '$75k - $110k' },
        { title: 'IoT Engineer', salary: '8k - 16k ج.م', salaryInt: '$65k - $95k' },
        { title: 'Electronics Design Engineer', salary: '7k - 15k ج.م', salaryInt: '$60k - $90k' },
        { title: 'Hardware Test Engineer', salary: '6k - 12k ج.م', salaryInt: '$55k - $80k' },
      ],
      roadmap: [
        { level: 'Beginner', period: '0-6 Months', items: ['Electronics Basics (Ohm\'s Law, R, C)', 'Digital Logic Gates', 'Arduino & C Programming', 'Using Oscilloscope & Multimeter'] },
        { level: 'Foundation', period: '6-12 Months', items: ['Digital Electronics (Flip-Flops, Counters)', 'AVR Microcontrollers (ATmega)', 'Communication Protocols (UART, I2C, SPI)', 'Breadboard Prototyping'] },
        { level: 'Intermediate', period: '12-18 Months', items: ['ARM Cortex-M (STM32)', 'Advanced C/C++ for Embedded', 'Sensors & Actuators', 'FreeRTOS Basics'] },
        { level: 'Advanced', period: '18-24 Months', items: ['PCB Design (KiCad/Eagle)', 'IoT Protocols (MQTT, BLE, Zigbee)', 'Low Power Design', 'Signal Analysis'] },
        { level: 'Professional', period: '24+ Months', items: ['Full Product Development', 'Power Optimization', 'Team Leadership', 'Professional Certs (ARM, IPC)'] },
      ],
    },
    modules: [
      { id: 'dig-elec', title: 'Digital Electronics', level: 'مبتدئ', time: '45 ساعة', cert: 'NTI Digital Electronics',
        overviewAr: 'أساسيات الإلكترونيات الرقمية: البوابات المنطقية، القلابات، العدادات، والسجلات. تحليل وتصميم الدوائر الرقمية.',
        overviewEn: 'Digital electronics fundamentals: logic gates, flip-flops, counters, and registers. Analyze and design digital circuits.',
        why: 'الإلكترونيات الرقمية هي الأساس الذي تبنى عليه جميع الأنظمة المدمجة.',
        concepts: ['Logic Gates (AND, OR, NOT, NAND, NOR, XOR)', 'Flip-Flops (SR, D, JK, T)', 'Counters (Sync & Async)', 'Karnaugh Maps & Boolean Algebra'],
        tools: ['Logisim', 'Multisim', 'Digital Logic Simulator'],
        applications: ['Counter circuit design', 'Traffic light control circuits'],
        mistakes: ['عدم التمييز بين الدوائر التوافقية والمتسلسلة', 'إهمال Glitches في التصميم'],
        summary: 'تفهم تصميم الدوائر الرقمية الأساسية التي تشكل قلب أي معالج.' },
      { id: 'avr-prog', title: 'AVR Microcontroller Programming', level: 'مبتدئ-متوسط', time: '60 ساعة', cert: 'NTI AVR',
        overviewAr: 'برمجة متحكمات AVR (ATmega32/328) بلغة C. GPIO، مقاطعات، مؤقتات، ADC.',
        overviewEn: 'AVR microcontroller programming in C. GPIO, interrupts, timers, and ADC conversion.',
        why: 'AVR منصة ممتازة لفهم بنية المتحكمات. Arduino يعتمد عليها.',
        concepts: ['GPIO Registers', 'External & Timer Interrupts', 'ADC', 'Timer/Counter Modes'],
        tools: ['Atmel/Microchip Studio', 'AVRDUDE', 'Proteus', 'Arduino IDE'],
        applications: ['Light control systems', 'Analog sensor reading'],
        mistakes: ['عدم تهيئة اتجاه GPIO', 'إهمال Debouncing', 'تجاوز تيار GPIO'],
        summary: 'برمجة AVR باحترافية وفهم بنية الـ Registers والمقاطعات.' },
      { id: 'arm-stm32', title: 'ARM Cortex-M & STM32', level: 'متوسط', time: '75 ساعة', cert: 'NTI ARM',
        overviewAr: 'برمجة STM32 باستخدام HAL Library: DMA، Timers، FreeRTOS، وتحكم حركي.',
        overviewEn: 'STM32 programming with HAL Library. DMA, advanced timers, FreeRTOS, and motor control.',
        why: 'ARM Cortex-M هو المعيار الصناعي في الأنظمة المدمجة.',
        concepts: ['STM32 HAL & LL Drivers', 'DMA (Direct Memory Access)', 'FreeRTOS Tasks & Queues', 'PWM & Motor Control'],
        tools: ['STM32CubeIDE', 'STM32CubeMX', 'Keil MDK'],
        applications: ['DC & Stepper motor control', 'Data logging with DMA'],
        mistakes: ['عدم تفعيل Clock للمحيطات', 'تسكين Priority خاطئ', 'إهمال Race Conditions في RTOS'],
        summary: 'كن مهندس ARM معتمد وقادر على تطوير أنظمة معقدة.' },
      { id: 'iot-protocols', title: 'IoT Protocols & Connectivity', level: 'متوسط-متقدم', time: '50 ساعة', cert: 'NTI IoT',
        overviewAr: 'MQTT، CoAP، Zigbee، BLE، LoRaWAN. ربط المتحكمات بالسحابة (AWS IoT).',
        overviewEn: 'IoT protocols: MQTT, CoAP, Zigbee, BLE, LoRaWAN. Connect MCUs to cloud (AWS IoT).',
        why: 'IoT هو المحرك الرئيسي للطلب على مهندسي الأنظمة المدمجة.',
        concepts: ['MQTT (Broker, Topics, QoS)', 'BLE Advertising & Services', 'Zigbee Mesh Networks', 'ESP32 Wi-Fi & HTTP'],
        tools: ['ESP32', 'Mosquitto MQTT', 'Node-RED', 'Wireshark'],
        applications: ['Smart weather station with cloud upload', 'Remote irrigation control'],
        mistakes: ['إرسال بيانات متكرر بدون تحسين', 'إهمال TLS', 'عدم التعامل مع انقطاع الشبكة'],
        summary: 'تصميم وتنفيذ أنظمة IoT كاملة من المتحكم للسحابة.' },
      { id: 'pcb-design', title: 'PCB Design & Fabrication', level: 'متقدم', time: '40 ساعة', cert: 'NTI PCB',
        overviewAr: 'تصميم لوحات PCB باستخدام KiCad: Schematic، Layout، Design Rules، Gerber.',
        overviewEn: 'PCB design with KiCad: schematic capture, layout, design rules, and Gerber file generation.',
        why: 'تصميم PCB يحول مشروعك من Breadboard إلى منتج قابل للتصنيع.',
        concepts: ['Schematic Capture', 'PCB Layers (Top, Bottom, Inner)', 'Design Rules (Clearance, Trace Width)', 'Gerber & BOM'],
        tools: ['KiCad', 'Eagle (Autodesk)', 'Altium Designer'],
        applications: ['Arduino Shield design', 'Custom control board for projects'],
        mistakes: ['توصيلات غير صحيحة في Schematic', 'عدم مراعاة Thermal Relief', 'توجيه مسارات بزوايا حادة'],
        summary: 'تصميم PCB احترافي جاهز للتصنيع وفق معايير الصناعة.' },
    ],
    glossary: [
      { term: 'Microcontroller (MCU)', arabic: 'متحكم دقيق', explanation: 'معالج متكامل مع ذاكرة و I/O على شريحة واحدة.', category: 'Hardware' },
      { term: 'GPIO', arabic: 'مدخل/مخرج عام', explanation: 'أطراف قابلة للبرمجة كمدخل أو مخرج.', category: 'Hardware' },
      { term: 'PWM', arabic: 'تعديل عرض النبضة', explanation: 'تقنية توليد إشارة بقيمة متوسطة متغيرة للتحكم في المحركات والإضاءة.', category: 'Concepts' },
      { term: 'ADC', arabic: 'محول تناظري رقمي', explanation: 'يحول الجهد التناظري إلى قيمة رقمية.', category: 'Hardware' },
      { term: 'I2C', arabic: 'بروتوكول I2C', explanation: 'اتصال تسلسلي بخطين (SDA, SCL) لأجهزة متعددة بعناوين فريدة.', category: 'Protocols' },
      { term: 'SPI', arabic: 'بروتوكول SPI', explanation: 'اتصال تسلسلي متزامن عالي السرعة بأربع إشارات.', category: 'Protocols' },
      { term: 'UART', arabic: 'بروتوكول UART', explanation: 'اتصال غير متزامن بخطي TX/RX لجهازين.', category: 'Protocols' },
      { term: 'MQTT', arabic: 'بروتوكول MQTT', explanation: 'بروتوكول Publish/Subscribe خفيف الوزن لـ IoT.', category: 'Protocols' },
      { term: 'RTOS', arabic: 'نظام تشغيل فوري', explanation: 'يدير تنفيذ المهام في الوقت الفعلي (FreeRTOS).', category: 'Software' },
      { term: 'PCB', arabic: 'لوحة دوائر مطبوعة', explanation: 'لوحة عازلة بمسارات نحاسية تربط المكونات إلكترونياً.', category: 'Hardware' },
      { term: 'ISR', arabic: 'دالة مقاطعة', explanation: 'تستدعى تلقائياً عند حدث مقاطعة لمعالجته فوراً.', category: 'Programming' },
      { term: 'Oscilloscope', arabic: 'أوسيلوسكوب', explanation: 'جهاز يعرض الجهد كرسم بياني مع الزمن لتحليل الإشارات.', category: 'Tools' },
      { term: 'Firmware', arabic: 'برمجيات ثابتة', explanation: 'برنامج مخزن في Flash يتحكم بعمل الجهاز.', category: 'Software' },
      { term: 'Breadboard', arabic: 'لوحة تجارب', explanation: 'لوحة بلاستيكية لبناء واختبار الدوائر بدون لحام.', category: 'Tools' },
      { term: 'DMA', arabic: 'وصول مباشر للذاكرة', explanation: 'ينقل البيانات بين الأجهزة والذاكرة بدون إشراف المعالج.', category: 'Hardware' },
    ],
    tools: [
      { name: 'KiCad', desc: 'برنامج مفتوح المصدر لتصميم PCB احترافي', use: 'تصميم لوحات دوائر مطبوعة متعددة الطبقات', pros: ['مجاني تماماً', 'مكتبات ضخمة', 'يدعم المشاريع المعقدة'], cons: ['واجهة أقل حداثة من Altium'], alt: 'Altium Designer, Eagle', demand: 'عالي جداً' },
      { name: 'STM32CubeMX', desc: 'أداة تكوين STM32 وتوليد كود C', use: 'تسريع تهيئة المتحكمات وتوليد كود HAL جاهز', pros: ['يولد كود جاهز', 'واجهة مرئية', 'يدمج مع IDEs'], cons: ['كود كبير الحجم', 'تبعيات غير ضرورية'], alt: 'STM32CubeIDE', demand: 'أساسي لمهندسي STM32' },
      { name: 'Proteus', desc: 'محاكاة دوائر إلكترونية ومتحكمات', use: 'اختبار الدوائر قبل التصنيع الفعلي', pros: ['يدعم AVR, PIC, ARM', 'مكتبة ضخمة', 'تصحيح أخطاء أثناء المحاكاة'], cons: ['ينقصه دعم متحكمات حديثة'], alt: 'LTspice', demand: 'مرتفع في الأكاديميا' },
      { name: 'FreeRTOS', desc: 'نظام تشغيل فوري مفتوح المصدر', use: 'تطبيقات تحتاج إدارة مهام متعددة فورية', pros: ['خفيف', 'يدعم Scheduling', 'منقول لأكثر من 40 معمارية'], cons: ['منحنى تعلم حاد'], alt: 'Zephyr RTOS', demand: 'عالي جداً' },
      { name: 'Logic Analyzer', desc: 'أداة تحليل الإشارات الرقمية', use: 'فحص بروتوكولات I2C, SPI, UART وتصحيح الأخطاء', pros: ['رخيص (USB)', 'سهل الاستخدام', 'يفتح نافذة على الإشارات'], cons: ['قنوات محدودة'], alt: 'Oscilloscope', demand: 'متوسط' },
    ],
    interview: [
      { type: 'hr', q: 'حدثنا عن نفسك وخبرتك في الأنظمة المدمجة.', a: 'خريج اتصالات وإلكترونيات، تدربت في NTI على الأنظمة المدمجة. أعملت مشاريع تحكم محرك DC بـ STM32 ونظام مراقبة حرارة بـ ESP32 مع AWS IoT.' },
      { type: 'hr', q: 'لماذا اخترت الأنظمة المدمجة؟', a: 'لأنه يجمع بين البرمجيات والعالم المادي. أحب أن أرى نتائج عملي تتحرك وتتفاعل مع البيئة.' },
      { type: 'technical', q: 'الفرق بين Microcontroller و Microprocessor؟', a: 'MCU: CPU + RAM + ROM + I/O على شريحة واحدة، للتطبيقات المحددة. MPU: مجرد CPU يحتاج لذاكرة خارجية، للحواسيب العامة.', difficulty: 'easy' },
      { type: 'technical', q: 'اشرح آلية ADC في المتحكمات.', a: 'ADC يحول الجهد لقيمة رقمية. Resolution يحدد البتات (مثلاً 10-bit = 1024 قيمة). العلاقة: Digital = (Vin / Vref) * (2^N - 1). اختيار Vref يؤثر على الدقة.', difficulty: 'medium' },
      { type: 'technical', q: 'قارن بين UART و I2C و SPI.', a: 'UART: خطان، غير متزامن، لجهازين فقط. I2C: خطان، عنونة لـ 127 جهاز، سرعة متوسطة. SPI: 4 خطوط، Full Duplex، عالي السرعة (حتى 50MHz).', difficulty: 'medium' },
      { type: 'scenario', q: 'جهاز IoT يعمل ببطارية ليثيوم لمدة سنة. كيف تصمم النظام لتقليل الطاقة؟', a: '1) MCU يدعم Sleep عميق (STM32L). 2) مقاطعات خارجية للإيقاظ. 3) خفض تردد Clock. 4) فصل طاقة الحساسات عبر MOSFET. 5) BLE بدلاً من Wi-Fi. 6) Buck Converter بكفاءة عالية.', difficulty: 'hard' },
      { type: 'scenario', q: 'منتجكم الإلكتروني يتعطل عند درجات حرارة فوق 50°C. شخّص المشكلة.', a: '1) فحص حرارة المكونات بكاميرا حرارية. 2) اختبار في Thermal Chamber. 3) مراجعة Datasheet للحدود الحرارية. الحلول: Heatsink، تحسين PCB Design، Thermal Shutdown في Firmware، مكونات Industrial Grade.', difficulty: 'hard' },
    ],
    career: [
      { level: 'Junior', exp: '0-2 years', title: 'Jr. Embedded Engineer', salary: '5k - 8k ج.م', skills: ['C Programming', 'AVR/Arduino', 'Digital Electronics'], certs: ['NTI Embedded Diploma'] },
      { level: 'Mid-Level', exp: '2-5 years', title: 'Embedded Engineer', salary: '8k - 15k ج.م', skills: ['ARM Cortex (STM32)', 'FreeRTOS', 'I2C/SPI/UART', 'PCB Design'], certs: ['ARM Certified'] },
      { level: 'Senior', exp: '5-8 years', title: 'Senior Firmware Engineer', salary: '15k - 25k ج.م', skills: ['System Architecture', 'Low Power Design', 'BLE/Wi-Fi/IoT'], certs: ['AWS IoT Specialty'] },
      { level: 'Lead', exp: '8+ years', title: 'Embedded Team Lead', salary: '25k - 40k ج.م', skills: ['Team Management', 'Product Lifecycle', 'Advanced PCB'], certs: ['PMP', 'CE/FCC Compliance'] },
    ],
    revision: {
      keyConcepts: ['MCU = CPU + RAM + ROM + I/O on one chip', 'Communication: SPI (fastest), I2C (addressing), UART (simplest)', 'FreeRTOS for real-time multi-tasking', 'PCB Design turns breadboard into product'],
      importantTerms: ['GPIO', 'ISR', 'RTOS', 'PWM', 'ADC', 'DMA', 'I2C/SPI/UART', 'MQTT'],
      mustTools: ['KiCad', 'STM32CubeIDE', 'FreeRTOS', 'Proteus', 'Logic Analyzer'],
      interviewNuggets: ['أتقن C Pointers و Bit Manipulation', 'ادرس Datasheet جيداً', 'جهز مشاريع على GitHub', 'تعلم Oscilloscope'],
    },
  },
  'digital-arts': {
    intro: {
      title: 'Digital Arts Track',
      subtitle: 'الفنون الرقمية',
      whatIs: 'الفنون الرقمية هو مجال يجمع بين الإبداع الفني والتكنولوجيا الرقمية لإنتاج محتوى بصري. يشمل التصميم الجرافيكي، الموشن جرافيك، تصميم واجهات المستخدم، والنمذجة ثلاثية الأبعاد باستخدام أحدث البرامج الاحترافية.',
      whatIsEn: 'Digital Arts combines creative expression with digital technology for visual content production. Includes graphic design, motion graphics, UI/UX design, and 3D modeling with professional tools.',
      importance: [
        { reason: 'الطلب المتزايد على المحتوى البصري', detail: 'وسائل التواصل والتسويق الرقمي تزيد الطلب على المصممين' },
        { reason: 'تنوع مجالات العمل', detail: 'الإعلانات، الألعاب، السينما، التلفزيون، تصميم المواقع' },
        { reason: 'عوائد مالية مجزية', detail: 'رواتب تنافسية وفرص عمل حر مربحة' },
        { reason: 'إبداع مستمر', detail: 'تحديات جديدة مع تطور التكنولوجيا والواقع الافتراضي' },
      ],
      applications: ['تصميم الهويات البصرية والشعارات', 'محتوى مرئي لوسائل التواصل', 'الموشن جرافيك والمؤثرات البصرية', 'تصميم واجهات وتجربة المستخدم', 'النمذجة ثلاثية الأبعاد'],
      careers: [
        { title: 'Graphic Designer', salary: '6k - 15k ج.م', salaryInt: '$50k - $80k' },
        { title: 'Motion Graphics Designer', salary: '8k - 20k ج.م', salaryInt: '$60k - $95k' },
        { title: 'UI/UX Designer', salary: '10k - 25k ج.م', salaryInt: '$70k - $110k' },
        { title: '3D Designer', salary: '8k - 20k ج.م', salaryInt: '$60k - $90k' },
        { title: 'Art Director', salary: '20k - 40k ج.م', salaryInt: '$90k - $140k' },
      ],
      roadmap: [
        { level: 'Beginner', period: '0-6 Months', items: ['Design Fundamentals (Color, Typography, Composition)', 'Adobe Photoshop Basics', 'Adobe Illustrator Basics', 'Social Media Content Design'] },
        { level: 'Foundation', period: '6-12 Months', items: ['Advanced Photoshop Techniques', 'Logo & Brand Identity Design', 'Typography & Layout Design', 'Figma for UI Design'] },
        { level: 'Intermediate', period: '12-18 Months', items: ['After Effects & Motion Graphics', 'UX Design Principles', 'Blender 3D Basics', 'Professional Portfolio'] },
        { level: 'Advanced', period: '18-24 Months', items: ['Advanced VFX', '3D Modeling & Animation', 'Design Project Management', 'Specialization (UI/UX, Motion, 3D)'] },
        { level: 'Professional', period: '24+ Months', items: ['Creative Direction & Team Leadership', 'Freelance & Brand Building', 'AR/VR Specialization', 'Open Source Contributions'] },
      ],
    },
    modules: [
      { id: 'design-fund', title: 'Graphic Design Fundamentals', level: 'مبتدئ', time: '25 ساعة', cert: 'Design Basics',
        overviewAr: 'أساسيات التصميم: نظرية الألوان، الطباعة، التكوين، والتواصل البصري.',
        overviewEn: 'Design fundamentals: color theory, typography, composition, and visual communication.',
        why: 'بدون أساسيات قوية، تظل المهارات التقنية غير مكتملة.',
        concepts: ['Color Theory & Harmonies', 'Typography & Font Selection', 'Composition Rules', 'Visual Hierarchy'],
        tools: ['Adobe Color', 'Coolors', 'Google Fonts'],
        applications: ['Analyzing any visual design', 'Creating balanced, attractive designs'],
        mistakes: ['ألوان متضاربة', 'خطوط كثيرة في تصميم واحد', 'إهمال المساحات البيضاء'],
        summary: 'أساسيات التصميم هي لغة التواصل البصري.' },
      { id: 'photoshop', title: 'Adobe Photoshop: Image Editing', level: 'مبتدئ', time: '35 ساعة', cert: 'Adobe Photoshop',
        overviewAr: 'تحرير الصور، الطبقات والأقنعة، تنميق، ودمج الصور.',
        overviewEn: 'Image editing, layers & masks, retouching, and compositing in Photoshop.',
        why: 'Photoshop هو المعيار الذهبي في صناعة التصميم.',
        concepts: ['Layers & Masks', 'Advanced Selection Tools', 'Color Grading', 'Retouching & Compositing'],
        tools: ['Adobe Photoshop', 'Nik Collection', 'Adobe Lightroom'],
        applications: ['Photo retouching', 'Advertisement and poster design'],
        mistakes: ['الإفراط في التنميق', 'العمل بدون طبقات', 'عدم حفظ نسخ احتياطية'],
        summary: 'Photoshop أقوى أداة لتحرير الصور والتصميم الرقمي.' },
      { id: 'illustrator', title: 'Adobe Illustrator: Vector & Brand Identity', level: 'متوسط', time: '35 ساعة', cert: 'Adobe Illustrator',
        overviewAr: 'تصميم Vector Graphics، شعارات، هويات بصرية، وطباعة فنية.',
        overviewEn: 'Vector graphics, logos, brand identity, and typographic design in Illustrator.',
        why: 'Illustrator هو الأداة الأولى لتصميم الهويات البصرية والشعارات.',
        concepts: ['Vector vs Raster', 'Brand Identity Design', 'Logo & Icon Design', 'Type Design'],
        tools: ['Adobe Illustrator', 'Affinity Designer', 'Inkscape'],
        applications: ['Complete brand identity kits', 'Vector infographics and illustrations'],
        mistakes: ['تصميم شعارات معقدة', 'استخدام رسومات نقطية', 'عدم تنظيم الطبقات'],
        summary: 'Illustrator عمود الهويات البصرية والرسوم المتجهة.' },
      { id: 'after-effects', title: 'After Effects: Motion Graphics', level: 'متوسط', time: '40 ساعة', cert: 'Adobe After Effects',
        overviewAr: 'موشن جرافيك: إطارات مفتاحية، تحريك نصوص وأشكال، مؤثرات وتركيب.',
        overviewEn: 'Motion graphics: keyframes, text/shape animation, visual effects, compositing.',
        why: 'في عصر الفيديو، الموشن جرافيك من أكثر المهارات طلباً.',
        concepts: ['Keyframes & Curves', 'Layers & Compositing', 'Tracking & Stabilization', 'Logo & Text Animation'],
        tools: ['Adobe After Effects', 'Adobe Premiere Pro', 'Cinema 4D Lite'],
        applications: ['Motion graphics ads', 'Visual effects for videos'],
        mistakes: ['إهمال Timing & Spacing', 'إفراط في المؤثرات', 'تجاهل إدارة الذاكرة'],
        summary: 'After Effects أقوى أداة للموشن جرافيك والمؤثرات.' },
      { id: 'ui-ux', title: 'UI/UX Design', level: 'متقدم', time: '30 ساعة', cert: 'UX Design',
        overviewAr: 'تصميم واجهات وتجربة المستخدم: أبحاث، Wireframes، Prototyping، اختبارات.',
        overviewEn: 'UI/UX design: user research, wireframes, prototyping, usability testing.',
        why: 'تجربة المستخدم لم تعد ترفاً. المواقع الناجحة تقدم تجربة سلسة.',
        concepts: ['User Research', 'Wireframing & Grid Systems', 'Interactive Prototyping', 'Usability Testing'],
        tools: ['Figma', 'Adobe XD', 'Sketch'],
        applications: ['Mobile app & website design', 'Redesigning existing product UX'],
        mistakes: ['واجهات معقدة', 'عدم الاتساق عبر الشاشات', 'عدم اختبار التصميم مع مستخدمين'],
        summary: 'UI/UX يجمع بين الإبداع وعلم النفس لتقديم تجارب رقمية متميزة.' },
      { id: 'blender-3d', title: 'Blender 3D Modeling', level: 'متقدم', time: '30 ساعة', cert: '3D Design',
        overviewAr: 'نمذجة ثلاثية الأبعاد: Modeling، Lighting، Materials، Animation، Rendering.',
        overviewEn: '3D modeling: modeling, lighting, materials, animation, and rendering in Blender.',
        why: 'التصميم ثلاثي الأبعاد أساسي في الإعلانات والألعاب والسينما.',
        concepts: ['Mesh Modeling', 'Three-Point Lighting', 'Materials & Texturing', 'Cycles & Eevee Rendering'],
        tools: ['Blender', 'Substance Painter', 'Poly Haven'],
        applications: ['3D product visualization', 'Architectural visualization'],
        mistakes: ['شبكات عالية الكثافة قبل الأوان', 'إضاءة غير احترافية'],
        summary: 'Blender يفتح عالم النمذجة ثلاثية الأبعاد مجاناً.' },
    ],
    glossary: [
      { term: 'Vector Graphics', arabic: 'رسوم متجهة', explanation: 'صور بمعادلات رياضية تحافظ على جودتها عند التكبير.', category: 'Design' },
      { term: 'Raster Graphics', arabic: 'رسوم نقطية', explanation: 'صور من بكسلز تفقد جودتها عند التكبير.', category: 'Design' },
      { term: 'Color Theory', arabic: 'نظرية الألوان', explanation: 'مبادئ تفاعل الألوان لتركيبات بصرية متناغمة.', category: 'Design' },
      { term: 'Typography', arabic: 'طباعة', explanation: 'فن تنظيم الحروف والنصوص لجعلها مقروءة وجذابة.', category: 'Design' },
      { term: 'Layer Mask', arabic: 'قناع طبقة', explanation: 'أداة غير مدمرة تخفي/تظهر أجزاء من الطبقة.', category: 'Photoshop' },
      { term: 'Keyframe', arabic: 'إطار مفتاحي', explanation: 'نقطة في الجدول الزمني تحدد قيمة خاصية في وقت معين.', category: 'Animation' },
      { term: 'Rendering', arabic: 'تصيير', explanation: 'تحويل النموذج ثلاثي الأبعاد لصورة نهائية.', category: '3D' },
      { term: 'Wireframe', arabic: 'هيكل نمطي', explanation: 'تمثيل مبسط للواجهة بدون ألوان.', category: 'UI/UX' },
      { term: 'Prototype', arabic: 'نموذج تفاعلي', explanation: 'محاكاة تفاعلية للتطبيق قبل البرمجة.', category: 'UI/UX' },
      { term: 'Brand Identity', arabic: 'هوية بصرية', explanation: 'مجموعة العناصر البصرية التي تمثل العلامة التجارية.', category: 'Branding' },
      { term: 'Motion Graphics', arabic: 'رسوم متحركة', explanation: 'تصميم متحرك يجمع الجرافيك والأنيميشن.', category: 'Animation' },
      { term: 'Compositing', arabic: 'تركيب بصري', explanation: 'دمج عناصر من مصادر متعددة في مشهد واحد.', category: 'VFX' },
      { term: 'UV Mapping', arabic: 'تخطيط UV', explanation: 'إسقاط نسيج ثنائي الأبعاد على نموذج ثلاثي الأبعاد.', category: '3D' },
      { term: 'Usability Testing', arabic: 'اختبار قابلية الاستخدام', explanation: 'تقييم المنتج مع مستخدمين حقيقيين.', category: 'UI/UX' },
      { term: 'DPI/PPI', arabic: 'دقة الصورة', explanation: 'DPI للطباعة، PPI للشاشة. كلما ارتفع زادت الجودة.', category: 'Technical' },
    ],
    tools: [
      { name: 'Adobe Photoshop', desc: 'تحرير الصور والتصميم الرقمي', use: 'تصميم إعلانات، تنميق، رسم رقمي', pros: ['إمكانيات غير محدودة', 'مجتمع ضخم', 'تكامل مع أدوبي'], cons: ['اشتراك شهري مرتفع'], alt: 'Affinity Photo, GIMP', demand: 'عالي جداً' },
      { name: 'Adobe Illustrator', desc: 'تصميم المتجهات والهويات البصرية', use: 'شعارات، هويات، أيقونات', pros: ['دقة عالية', 'أدوات طباعة', 'تكامل'], cons: ['مكلف', 'بطيء في ملفات كبيرة'], alt: 'Affinity Designer, Inkscape', demand: 'عالي جداً' },
      { name: 'Adobe After Effects', desc: 'موشن جرافيك ومؤثرات بصرية', use: 'أنيميشن، مؤثرات، تركيب', pros: ['إمكانيات تحريك', 'إضافات (Plugins)', 'نتائج سينمائية'], cons: ['منحنى تعلم حاد'], alt: 'DaVinci Resolve Fusion', demand: 'عالي جداً' },
      { name: 'Figma', desc: 'تصميم واجهات ونماذج تفاعلية', use: 'UI/UX، تعاون جماعي', pros: ['مجاني', 'تعاون مباشر', 'مكتبة مجتمعية'], cons: ['نظام ملفات محلي محدود'], alt: 'Sketch, Adobe XD', demand: 'عالي جداً' },
      { name: 'Blender', desc: 'برنامج نمذجة ثلاثية الأبعاد مفتوح المصدر', use: 'موديلينج، أنيميشن، إضاءة', pros: ['مجاني', 'مجتمع نشط', 'تحديثات مستمرة'], cons: ['واجهة غير تقليدية'], alt: 'Cinema 4D, Maya', demand: 'متزايد' },
    ],
    interview: [
      { type: 'hr', q: 'حدثني عن نفسك وخبرتك في التصميم.', a: 'خريج مسار الفنون الرقمية في NTI. أجيد Photoshop, Illustrator, After Effects, Figma. عملت على هويات بصرية ومحتوى سوشيال ميديا وموشن جرافيك.' },
      { type: 'hr', q: 'لماذا تريد العمل في هذه الشركة؟', a: 'أعجبني أسلوب الشركة في التصاميم الإبداعية وأرى أن مهاراتي تضيف قيمة للفريق.' },
      { type: 'technical', q: 'الفرق بين Vector و Raster ومتى تستخدم كل منهما؟', a: 'Vector: معادلات رياضية، تتكبير بلا حدود، للشعارات. Raster: بكسلز، للصور الفوتوغرافية. للشعارات Illustrator، للصور Photoshop.', difficulty: 'easy' },
      { type: 'technical', q: 'اشرح Layer Masks في Photoshop.', a: 'تخفي أجزاء من الطبقة بشكل غير مدمر (Non-Destructive). يمكن الرجوع وتعديلها بأي وقت، عكس Eraser الذي يحذف البكسلز نهائياً.', difficulty: 'easy' },
      { type: 'technical', q: 'كيف تصمم واجهة تطبيق جوال مع تجربة مستخدم جيدة؟', a: 'أبدأ بأبحاث المستخدم، شخصيات وسيناريوهات، Wireframe، تصميم بصري في Figma، Prototype تفاعلي، اختبار مع مستخدمين حقيقيين.', difficulty: 'medium' },
      { type: 'scenario', q: 'عميل طلب تغيير شعار اكتمل بالكامل بعد أسبوع عمل. تتعامل إزاي؟', a: 'أستمع لملاحظاته بهدوء. أشرح نقاط القوة في التصميم الحالي. لو التغيير مبرر، أقدم 2-3 بدائل مع مراعاة الوقت الإضافي.', difficulty: 'hard' },
      { type: 'scenario', q: 'خلاف في فريق التصميم حول الاتجاه البصري للمشروع. بماذا تنصح؟', a: 'جلسة عصف ذهني، كل شخص يقدم رؤيته. نصنع Mockup لكل اتجاه ونختبره مع عينة مستخدمين. البيانات أحسم من الآراء. تصويت ديمقراطي أو الرجوع للمدير.', difficulty: 'hard' },
    ],
    career: [
      { level: 'Junior', exp: '0-2 years', title: 'Jr. Graphic Designer', salary: '5k - 8k ج.م', skills: ['Photoshop', 'Illustrator', 'Design Basics', 'Social Media Content'], certs: ['Design Fundamentals'] },
      { level: 'Mid-Level', exp: '2-5 years', title: 'Graphic / Motion Designer', salary: '8k - 15k ج.م', skills: ['After Effects', 'Figma', 'Brand Identity', 'Client Communication'], certs: ['Adobe Certified', 'UI/UX'] },
      { level: 'Senior', exp: '5-8 years', title: 'Senior Creative Designer', salary: '15k - 25k ج.م', skills: ['Team Leadership', 'Blender', 'Creative Direction', 'Brand Strategy'], certs: ['Project Management'] },
      { level: 'Lead', exp: '8+ years', title: 'Art Director / Creative Lead', salary: '25k - 40k+ ج.م', skills: ['Creative Vision', 'Large Team Management', 'Strategic Planning'], certs: ['Advanced Creative Mgmt'] },
    ],
    revision: {
      keyConcepts: ['Design Principles: Balance, Contrast, Unity, Rhythm', 'Vector vs Raster', 'UI/UX: User research to prototyping', '3D: Modeling, Lighting, Materials'],
      importantTerms: ['Layer/Mask (PS)', 'Path/Anchor (AI)', 'Keyframe/Timeline (AE)', 'Auto Layout (Figma)'],
      mustTools: ['Photoshop', 'Illustrator', 'After Effects', 'Figma', 'Blender'],
      interviewNuggets: ['البورتفوليو أقوى ما تملك', 'Storytelling في عرض الأعمال', 'المبادئ أهم من الأدوات', 'جهز 3 مشاريع كاملة'],
    },
  },
  'digital-marketing': {
    intro: {
      title: 'Digital Marketing Track',
      subtitle: 'التسويق الرقمي',
      whatIs: 'التسويق الرقمي هو استخدام القنوات الرقمية مثل محركات البحث ومواقع التواصل والبريد الإلكتروني والمواقع للترويج للمنتجات والخدمات وبناء العلامات التجارية، مع الاعتماد على تحليل البيانات لتحقيق أقصى عائد على الاستثمار.',
      whatIsEn: 'Digital marketing uses digital channels such as search engines, social media, email, and websites to promote products and build brands, leveraging data analytics to maximize ROI.',
      importance: [
        { reason: 'الوصول العالمي', detail: 'القنوات الرقمية توصل لجمهور عالمي بتكلفة منخفضة' },
        { reason: 'استهداف دقيق', detail: 'استهداف العملاء بالعمر والموقع والاهتمامات بدقة' },
        { reason: 'قياس العائد', detail: 'أدوات تحليل لقياس أداء الحملات وعائد الاستثمار فورياً' },
        { reason: 'مرونة عالية', detail: 'تعديل الحملات في الوقت الفعلي لتحسين الأداء' },
      ],
      applications: ['التجارة الإلكترونية', 'العلامات التجارية والشركات الناشئة', 'المؤسسات التعليمية', 'القطاع الخدمي والسياحي', 'التطبيقات والمنصات الرقمية'],
      careers: [
        { title: 'Digital Marketing Specialist', salary: '8k - 15k ج.م', salaryInt: '$55k - $80k' },
        { title: 'SEO Specialist', salary: '10k - 18k ج.م', salaryInt: '$60k - $90k' },
        { title: 'Social Media Manager', salary: '8k - 14k ج.م', salaryInt: '$50k - $75k' },
        { title: 'PPC / Google Ads Specialist', salary: '12k - 20k ج.م', salaryInt: '$65k - $95k' },
        { title: 'Digital Marketing Manager', salary: '18k - 30k ج.م', salaryInt: '$80k - $120k' },
      ],
      roadmap: [
        { level: 'Beginner', period: '0-6 Months', items: ['Digital Marketing Fundamentals', 'Marketing Funnel & Customer Journey', 'Content Writing Basics', 'Intro to SEO'] },
        { level: 'Foundation', period: '6-12 Months', items: ['Social Media Marketing (FB, IG)', 'Google Ads Fundamentals', 'Email Marketing (Mailchimp)', 'Google Analytics Basics'] },
        { level: 'Intermediate', period: '12-18 Months', items: ['Advanced SEO (Technical)', 'LinkedIn & TikTok Ads', 'Conversion Rate Optimization', 'PPC Campaign Management'] },
        { level: 'Advanced', period: '18-24 Months', items: ['Data-Driven Marketing', 'Marketing Automation', 'A/B Testing & Analytics', 'Affiliate Marketing'] },
        { level: 'Professional', period: '24+ Months', items: ['Full Marketing Strategy', 'Multi-Channel Campaigns', 'Team Leadership', 'Google/Meta Certifications'] },
      ],
    },
    modules: [
      { id: 'dm-fund', title: 'Digital Marketing Fundamentals', level: 'مبتدئ', time: '15 ساعة', cert: 'HubSpot Digital Marketing',
        overviewAr: 'مقدمة شاملة للتسويق الرقمي: قمع التسويق، رحلة العميل، استراتيجيات التسويق.',
        overviewEn: 'Comprehensive intro: marketing funnel, customer journey, and digital marketing strategies.',
        why: 'أساس يبنى عليه كل محتوى الدورة. فهم قمع التسويق ورحلة العميل ضروري.',
        concepts: ['Marketing Funnel (AIDA)', 'Customer Journey Mapping', 'Digital Channels', 'KPI & OKR Definition'],
        tools: ['Google Trends', 'Canva', 'HubSpot', 'SimilarWeb'],
        applications: ['Building a complete marketing strategy', 'Choosing right channels for target audience'],
        mistakes: ['البدء بدون استراتيجية', 'التواجد على كل القنوات', 'إهمال تحليل الجمهور'],
        summary: 'حجر الأساس لكل مسوق رقمي.' },
      { id: 'seo', title: 'Search Engine Optimization (SEO)', level: 'متوسط', time: '20 ساعة', cert: 'Google SEO',
        overviewAr: 'تحسين محركات البحث: On-page، Off-page، Technical SEO.',
        overviewEn: 'SEO: on-page, off-page, and technical optimization for top search rankings.',
        why: 'SEO أهم قناة تسويق مستدامة توفر زيارات عضوية بدون تكلفة إعلانية.',
        concepts: ['Keyword Research', 'On-Page (Meta, Headings, Content)', 'Off-Page (Backlinks)', 'Technical SEO (Speed, Indexing)'],
        tools: ['Google Search Console', 'Ahrefs', 'SEMrush', 'Yoast SEO', 'GTmetrix'],
        applications: ['Improving site search rankings', 'Increasing organic traffic'],
        mistakes: ['حشو الكلمات المفتاحية', 'إهمال تجربة المستخدم', 'روابط خلفية منخفضة الجودة'],
        summary: 'SEO عمود التسويق الرقمي المستدام.' },
      { id: 'social-media', title: 'Social Media Marketing', level: 'مبتدئ', time: '18 ساعة', cert: 'Meta Certified',
        overviewAr: 'التسويق عبر منصات التواصل: فيسبوك، إنستغرام، لينكد إن، تيك توك.',
        overviewEn: 'Social media marketing: Facebook, Instagram, LinkedIn, TikTok advertising.',
        why: 'منصات التواصل الأكثر استخداماً في العالم العربي.',
        concepts: ['Content Strategy & Calendar', 'Facebook & Instagram Ads', 'LinkedIn Advertising', 'TikTok Ads'],
        tools: ['Meta Business Suite', 'Hootsuite', 'Buffer', 'Canva'],
        applications: ['Social media ad campaigns', 'Building digital communities'],
        mistakes: ['نشر بدون استراتيجية', 'إهمال التفاعل', 'اعتماد على المدفوع فقط'],
        summary: 'إدارة حملات احترافية على جميع منصات التواصل.' },
      { id: 'google-ads', title: 'Google Ads & PPC', level: 'متوسط', time: '20 ساعة', cert: 'Google Ads',
        overviewAr: 'إعلانات Google: Search، Display، Video، Shopping مع إدارة الميزانية.',
        overviewEn: 'Google Ads: Search, Display, Video, Shopping campaigns with budget management.',
        why: 'Google Ads أكبر منصة إعلانية بأعلى عائد استثمار.',
        concepts: ['Search Campaigns & Keywords', 'Display & Remarketing', 'YouTube Ads', 'Shopping Campaigns', 'Quality Score'],
        tools: ['Google Ads', 'Keyword Planner', 'Google Merchant Center'],
        applications: ['Search ad campaigns', 'Remarketing for e-commerce'],
        mistakes: ['إهمال الكلمات السلبية', 'عدم تتبع التحويلات', 'إدارة الميزانية غير فعالة'],
        summary: 'إدارة حملات Google Ads احترافية.' },
      { id: 'email-content', title: 'Email & Content Marketing', level: 'متوسط', time: '15 ساعة', cert: 'HubSpot Content',
        overviewAr: 'التسويق بالبريد الإلكتروني وإنشاء المحتوى: تدوين، فيديو، إنفوجرافيك.',
        overviewEn: 'Email marketing and content creation: blogging, video, infographics.',
        why: 'البريد الإلكتروني أعلى عائد استثمار، والمحتوى جوهر التسويق الرقمي.',
        concepts: ['List Building & Segmentation', 'Email Automation & Drip Campaigns', 'Content Writing', 'Video Content'],
        tools: ['Mailchimp', 'HubSpot CRM', 'Grammarly', 'Canva'],
        applications: ['Email drip campaigns', 'Blog and video content creation'],
        mistakes: ['إرسال بدون تقسيم الجمهور', 'إهمال تصميم الموبايل', 'محتوى طويل بدون قيمة'],
        summary: 'أقوى قناتين من حيث العائد والتأثير.' },
      { id: 'analytics', title: 'Google Analytics & Affiliate Marketing', level: 'متقدم', time: '18 ساعة', cert: 'Google Analytics',
        overviewAr: 'تحليل حركة المرور، تتبع التحويلات، والتسويق بالعمولة والمؤثرين.',
        overviewEn: 'Traffic analysis, conversion tracking, affiliate and influencer marketing.',
        why: 'تحليل البيانات أساس اتخاذ القرارات التسويقية الصحيحة.',
        concepts: ['GA4 Setup & Config', 'Traffic Source Analysis', 'Conversion Tracking', 'Affiliate Programs', 'Influencer Strategy'],
        tools: ['Google Analytics 4', 'Google Tag Manager', 'ShareASale', 'Upfluence'],
        applications: ['Campaign performance analysis', 'Building affiliate programs'],
        mistakes: ['عدم إعداد تتبع التحويلات', 'مؤثرين غير مناسبين', 'إهمال تحليل السلوك'],
        summary: 'مهارات تحليلية وتسويقية لاتخاذ قرارات مبنية على البيانات.' },
    ],
    glossary: [
      { term: 'Marketing Funnel', arabic: 'قمع التسويق', explanation: 'نموذج يصف رحلة العميل من الوعي للشراء.', category: 'Strategy' },
      { term: 'SEO', arabic: 'تحسين محركات البحث', explanation: 'ممارسات لتحسين ظهور الموقع في نتائج البحث.', category: 'SEO' },
      { term: 'PPC', arabic: 'الدفع مقابل النقرة', explanation: 'نموذج إعلاني تدفع عن كل نقرة.', category: 'Ads' },
      { term: 'CTR', arabic: 'نسبة النقر', explanation: 'نسبة النقرات إلى مرات الظهور.', category: 'Analytics' },
      { term: 'Conversion Rate', arabic: 'معدل التحويل', explanation: 'نسبة الزوار الذين أكملوا إجراءً مستهدفاً.', category: 'Analytics' },
      { term: 'Quality Score', arabic: 'درجة الجودة', explanation: 'مقياس Google لجودة الإعلان والكلمة المفتاحية.', category: 'Ads' },
      { term: 'Backlinks', arabic: 'روابط خلفية', explanation: 'روابط من مواقع خارجية لموقعك، عامل مهم في SEO.', category: 'SEO' },
      { term: 'Remarketing', arabic: 'إعادة استهداف', explanation: 'استهداف الزوار السابقين للموقع.', category: 'Ads' },
      { term: 'Drip Campaign', arabic: 'حملة تنقيط', explanation: 'سلسلة رسائل بريدية تلقائية حسب سلوك المستخدم.', category: 'Email' },
      { term: 'Landing Page', arabic: 'صفحة مقصودة', explanation: 'صفحة مصممة لتحويل الزوار لعملاء.', category: 'Optimization' },
      { term: 'ROI', arabic: 'عائد الاستثمار', explanation: 'مقارنة الربح بتكلفة الحملة التسويقية.', category: 'Analytics' },
      { term: 'Organic Traffic', arabic: 'زيارة عضوية', explanation: 'زوار عبر نتائج البحث الطبيعية.', category: 'Analytics' },
      { term: 'A/B Testing', arabic: 'اختبار منفصل', explanation: 'مقارنة نسختين من إعلان لاختبار الأداء.', category: 'Optimization' },
      { term: 'Influencer Marketing', arabic: 'تسويق مؤثرين', explanation: 'التعاون مع شخصيات مؤثرة للترويج.', category: 'Strategy' },
      { term: 'Impressions', arabic: 'مرات الظهور', explanation: 'عدد مرات عرض الإعلان للمستخدمين.', category: 'Analytics' },
    ],
    tools: [
      { name: 'Google Analytics 4', desc: 'تحليل حركة المرور وسلوك المستخدمين', use: 'تحليل مصادر الزيارات وتتبع التحويلات', pros: ['مجاني', 'تكامل مع Google', 'تقارير شاملة'], cons: ['منحنى تعلم حاد'], alt: 'Matomo', demand: 'أساسي لكل مسوق' },
      { name: 'SEMrush', desc: 'منصة SEO وتحليل المنافسين', use: 'بحث كلمات مفتاحية، تحليل روابط، تدقيق موقع', pros: ['قاعدة بيانات ضخمة', 'أدوات متعددة', 'تقارير تنافسية'], cons: ['باهظ الثمن'], alt: 'Ahrefs', demand: 'مرتفع' },
      { name: 'Meta Business Suite', desc: 'إدارة إعلانات فيسبوك وإنستغرام', use: 'إنشاء وإدارة وتحليل الحملات الإعلانية', pros: ['مجاني', 'تكامل', 'استهداف دقيق'], cons: ['واجهة معقدة', 'تحديثات سياسات'], alt: 'Snapchat Ads', demand: 'مرتفع جداً' },
      { name: 'Mailchimp', desc: 'منصة أتمتة التسويق بالبريد الإلكتروني', use: 'بناء قوائم بريدية وحملات أتمتة', pros: ['سهل', 'قوالب جاهزة', 'خطة مجانية'], cons: ['التسعير يزيد مع الحجم'], alt: 'ConvertKit', demand: 'مرتفع' },
      { name: 'Google Search Console', desc: 'مراقبة أداء الموقع في بحث Google', use: 'مراقبة الفهرسة وتحليل الكلمات المفتاحية', pros: ['مجاني', 'بيانات من Google', 'تنبيهات'], cons: ['ميزات محدودة'], alt: 'Bing Webmaster', demand: 'مرتفع جداً' },
      { name: 'Canva', desc: 'أداة تصميم جرافيك سهلة', use: 'تصميم منشورات سوشيال ميديا وإنفوجرافيك', pros: ['سهل', 'قوالب احترافية', 'مجاني قوي'], cons: ['ميزات احترافية محدودة'], alt: 'Adobe Express', demand: 'مرتفع' },
    ],
    interview: [
      { type: 'hr', q: 'What is the marketing funnel and why is it important?', a: 'The marketing funnel describes the customer journey from awareness to purchase. It helps marketers understand behavior, optimize each stage, and allocate budget effectively.' },
      { type: 'hr', q: 'Why digital marketing and what skills do you bring?', a: 'I love the blend of creativity and data analysis. I bring SEO, social media, Google Ads, and analytics skills with the ability to adapt quickly to new platforms.' },
      { type: 'technical', q: 'Difference between On-page and Off-page SEO?', a: 'On-page: optimizations within your site (meta tags, content). Off-page: external factors (backlinks, social signals). Example: optimizing title tags vs guest blogging for backlinks.', difficulty: 'easy' },
      { type: 'technical', q: 'How does Quality Score affect Google Ads campaigns?', a: 'Quality Score measures relevance of keywords, ads, and landing pages. Higher scores = lower CPC and better ad positions. Based on expected CTR, ad relevance, and landing page experience.', difficulty: 'medium' },
      { type: 'technical', q: 'How do you set up conversion tracking in GA4?', a: 'Identify key events (purchase, sign-up), mark them as conversions in GA4 Events section, or create custom events via Google Tag Manager. Marked events appear in Conversions report.', difficulty: 'medium' },
      { type: 'scenario', q: 'Client site traffic dropped 40% overnight. Diagnose and fix?', a: '1) Check Google Search Console for manual actions. 2) GA for traffic source breakdown. 3) GTmetrix for site speed. 4) Check algorithm updates. 5) Inspect robots.txt, sitemap, server errors.', difficulty: 'hard' },
      { type: 'scenario', q: '10,000 EGP monthly budget for Google Ads - how to allocate?', a: '60% Search (high-intent), 20% Remarketing, 10% Display (awareness), 10% YouTube. Monitor weekly and reallocate based on ROAS and conversion data.', difficulty: 'hard' },
    ],
    career: [
      { level: 'Junior', exp: '0-2 years', title: 'Digital Marketing Executive', salary: '6k - 10k ج.م', skills: ['Social Media', 'Content Creation', 'Basic SEO'], certs: ['Google Digital Garage'] },
      { level: 'Mid-Level', exp: '2-5 years', title: 'Digital Marketing Specialist', salary: '10k - 18k ج.م', skills: ['SEO & SEM', 'Google Ads', 'Email Automation', 'Analytics'], certs: ['Google Ads Certified', 'HubSpot'] },
      { level: 'Senior', exp: '5-8 years', title: 'Senior Marketing Manager', salary: '18k - 28k ج.م', skills: ['Campaign Strategy', 'Team Management', 'Budget Planning'], certs: ['Meta Certified', 'GA Certified'] },
      { level: 'Lead', exp: '8+ years', title: 'Head of Digital Marketing', salary: '28k - 45k ج.م', skills: ['Strategic Leadership', 'Brand Strategy', 'ROI Optimization'], certs: ['PMP', 'MBA'] },
    ],
    revision: {
      keyConcepts: ['Marketing Funnel (Awareness, Interest, Desire, Action)', 'SEO (On-page, Off-page, Technical)', 'PPC & Google Ads', 'Email Automation & Segmentation', 'Analytics & Conversion Tracking'],
      importantTerms: ['CTR', 'ROI', 'Quality Score', 'Bounce Rate', 'Conversion Rate', 'Impressions'],
      mustTools: ['Google Analytics 4', 'Google Search Console', 'SEMrush', 'Meta Business Suite', 'Mailchimp'],
      interviewNuggets: ['افهم Marketing Funnel بعمق', 'اعرف تحسب ROI و CAC', 'جهز نتائج حملات حقيقية', 'Portfolio من أعمالك'],
    },
  },
};
